/* =========================================================================
   かけいぼ ― 変異の一覧（わざと壊す内容の台帳）
   -------------------------------------------------------------------------
   ここは「一覧」だけを持つ。実際に走らせる仕組みは mutation-lib.js にある。
   分けた理由は、ふだんの検査（高速）と完全検査の両方から、
   まったく同じ一覧を読ませるため。二重管理にすると必ずズレる。

   1件 ＝ 「守りたい振る舞い」1つ。
     name   … わざと壊す内容
     guards … それで守りたい振る舞い
     file   … 壊す先（core.js / index.html / sw.js）
     from   … 置きかえる前の文字列（ソースにそのまま在ること）
     to     … 置きかえた後の文字列
   ========================================================================= */
const MUTATIONS = [
  /* ---- 先取りと支出の分け方・iDeCo・各種保険 ---- */
  { name: "借入を先取りに戻す", guards: "出ていくお金は支出として数える",
    file: "core.js", from: '    if (loan > 0) rows.push({ key: "loans", name: "借入の返済", amount: loan });', to: "" },
  { name: "各種保険を支出に入れない", guards: "保険料は毎月固定の支出",
    file: "core.js", from: '    if (ins > 0) rows.push({ key: "insurance", name: "生命保険の保険料", amount: ins });', to: "" },
  { name: "出ていくお金を毎月固定に数えない", guards: "毎月固定に入る",
    file: "core.js", from: "    const recurringSpend = sum(expRecs.filter(isRecurring), function (t) { return t.amount; }) + lpSpendSum;",
    to: "    const recurringSpend = sum(expRecs.filter(isRecurring), function (t) { return t.amount; });" },
  { name: "出ていくお金を先取りにも足す", guards: "二重に引かない",
    file: "core.js", from: "    const setAside = nisaPlanned + lpSetAsideSum;",
    to: "    const setAside = nisaPlanned + lpSetAsideSum + lpSpendSum;" },
  { name: "iDeCoの掛金を先取りに入れない", guards: "iDeCoの掛金も先取りとして引く",
    file: "core.js", from: '    if (ide > 0) rows.push({ key: "ideco", name: "iDeCoの掛金", amount: ide });', to: "" },
  { name: "iDeCo・各種保険を渡さない", guards: "ライフプランへ渡す",
    file: "core.js", from: "        insurancePolicies: a.insurancePolicies,", to: "" },
  { name: "記録の選択に保険を残す", guards: "入力口はライフプラン欄だけ",
    file: "core.js", from: '    { k: "insure",   e: "🛟", n: "保険", hidden: true },', to: '    { k: "insure",   e: "🛟", n: "保険" },' },
  { name: "記録の選択に私年金を残す", guards: "入力口はライフプラン欄だけ",
    file: "core.js", from: '    { k: "pension",  e: "💰", n: "私年金", hidden: true },', to: '    { k: "pension",  e: "💰", n: "私年金" },' },
  { name: "まとめで先取りと支出を分けない", guards: "先取りと毎月固定の支出を分けて出す",
    file: "index.html", from: '    html += `<div class="stitle">${T("sum.fixedTitle")}</div>', to: '    html += `<div class="stitle">${T("sum.setAsideTitle")}</div>' },

  /* ---- 毎月の先取り・一括投資・銘柄の内訳 ---- */
  { name: "毎月の金額を先取りに入れない", guards: "毎月の金額は先取りとして引かれる",
    file: "core.js", from: "    const setAside = nisaPlanned + lpSetAsideSum;", to: "    const setAside = nisaPlanned;" },
  { name: "毎月の金額を支出にも足す", guards: "支出には足さない（二重に引かない）",
    file: "core.js", from: "    const available = incomeTotal - spendTotal - setAside;", to: "    const available = incomeTotal - spendTotal - setAside - lpSetAsideSum;" },
  { name: "一括投資も毎月の計算に入れる", guards: "一括投資はかけいぼの計算に入れない",
    file: "core.js", from: '    if (a.gold.monthlyYen > 0) rows.push({ key: "gold", name: "金（きん）の積立", amount: a.gold.monthlyYen });',
    to: '    if (a.gold.monthlyYen > 0) rows.push({ key: "gold", name: "金（きん）の積立", amount: a.gold.monthlyYen });\n    a.lumpSums.forEach(function (l) { rows.push({ key: "lump", name: "一括投資", amount: l.amount }); });' },
  { name: "月額を銘柄の合計にしない", guards: "月額は銘柄の合計（打つ場所は1か所）",
    file: "core.js", from: "        monthlyYen: funds.length ? sum : lpNum(row.monthlyYen, 1e9),", to: "        monthlyYen: lpNum(row.monthlyYen, 1e9)," },
  { name: "一括投資をライフプランへ渡さない", guards: "一括投資は渡す",
    file: "core.js", from: "        lumpSums: a.lumpSums,\n        insurancePolicies", to: "        insurancePolicies" },
  { name: "まとめに先取りの内わけを出さない", guards: "毎月固定（先取り）の内わけを出す",
    file: "index.html", from: "    ${lpMonthlyCard(c)}", to: "" },
  { name: "NISAのタイルを古い設定欄へ飛ばす", guards: "NISAの入力口は内訳だけ",
    file: "index.html", from: '<button class="ds" data-act="lp-open" data-kind="nisa">',
    to: '<button class="ds" data-go="settings" data-focus="f-nisa">' },

  /* ---- 生年月日とNISA積立のスケジュール ---- */
  { name: "年齢の数え方を1年ずらす", guards: "生年月日から出す年齢",
    file: "core.js", from: "    return years + (nt - from) / span;", to: "    return years + (nt - from) / span + 1;" },
  { name: "おかしな生年月日も受け入れる", guards: "妥当な生年月日だけ残す",
    file: "core.js", from: "    return validateDateString(s) ? s : \"\";", to: "    return s;" },
  { name: "未来の生年月日を受け入れる", guards: "未来の生年月日は使わない",
    file: "core.js", from: "    if (!Number.isFinite(bt) || !Number.isFinite(nt) || nt < bt) return null;",
    to: "    if (!Number.isFinite(bt) || !Number.isFinite(nt)) return null;" },
  { name: "区間の終わりを含めない", guards: "終了年齢は含む",
    file: "core.js", from: "      return (age >= r.fromAge && age <= r.toAge) ? sum + r.monthlyYen : sum;",
    to: "      return (age >= r.fromAge && age < r.toAge) ? sum + r.monthlyYen : sum;" },
  { name: "逆さまの区間をそのまま通す", guards: "終わりが始まりより前なら、始まりにそろえる",
    file: "core.js", from: "        toAge: to < from ? from : to,", to: "        toAge: to," },
  { name: "生年月日が無くても自動にする", guards: "そろっていないうちは手入力のまま",
    file: "core.js", from: "    return !!normalizeBirth(s.birth) && hasSchedule;", to: "    return hasSchedule;" },
  { name: "NISAのスケジュールを渡さない", guards: "スケジュールと銘柄もライフプランへ渡す",
    file: "core.js", from: "        tsumitateSchedule: a.tsumitateSchedule.map(strip),\n        growthSchedule: a.growthSchedule.map(strip),", to: "" },
  { name: "生年月日を拾わない", guards: "生年月日を保存できる",
    file: "index.html", from: '  s.birth=Core.normalizeBirth(g("f-birth"));\n  s.goalName=(g("f-gname")||"").slice(0,24);',
    to: '  s.goalName=(g("f-gname")||"").slice(0,24);' },
  { name: "先取り貯金の欄を設定へ戻す（銀行貯金と二重）", guards: "打ち込む欄はひとつだけ",
    file: "index.html", from: '    <div class="stitle" style="margin-top:6px">${T("set.birth")}</div>',
    to: '    <div class="field"><label>先取り貯金（月・予定額）</label><input id="f-save"></div>\n    <div class="stitle" style="margin-top:6px">${T("set.birth")}</div>' },
  { name: "タイルを横スクロールに戻す（隠れた分に気づけない）", guards: "隠れずに全部見える2段の並び",
    file: "index.html", from: "  .dreamstrip{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}",
    to: "  .dreamstrip{display:flex;gap:8px;overflow-x:auto}" },
  { name: "生年月日を保存しない", guards: "生年月日を保存できる",
    file: "index.html", from: '  s.birth=Core.normalizeBirth(g("f-birth"));\n  s.goalName=(g("f-gname")||"").slice(0,24);\n  /* 打ち込みは主単位。内部の最小単位へ直してから設定に入れる。 */',
    to: '  s.goalName=(g("f-gname")||"").slice(0,24);\n  /* 打ち込みは主単位。内部の最小単位へ直してから設定に入れる。 */' },

  /* ---- ライフプランへ渡す資産（金・銀行貯金・借入金・民間年金） ---- */
  { name: "渡す形の入れものを変える", guards: "ライフプランが受け取れる { inputs: ... } の形",
    file: "core.js", from: '      source: "kakeibo",', to: '      source: "other",' },
  { name: "ライフプランの入力まで上書きする", guards: "渡すのは4つだけ",
    file: "core.js", from: "        insurancePolicies: a.insurancePolicies,\n      });", to: "        insurancePolicies: a.insurancePolicies,\n        banksExtra: [{ x: 1 }],\n      });" },
  { name: "件数の上限を外す", guards: "1種類あたりの行数に上限がある",
    file: "core.js", from: "  const LP_MAX_ROWS = 20;", to: "  const LP_MAX_ROWS = 100000;" },
  { name: "マイナスの金額を受け入れる", guards: "読み取れない値・マイナスは0にする",
    file: "core.js", from: "    if (!Number.isFinite(n) || n < 0) return 0;", to: "    if (!Number.isFinite(n)) return 0;" },
  { name: "金の評価額を足し算にする", guards: "金は「量 × 1グラムの値段」",
    file: "core.js", from: "    return Math.round(g.currentGrams * g.pricePerGram);", to: "    return Math.round(g.currentGrams + g.pricePerGram);" },
  { name: "空でも設定に持たせる", guards: "何も入れていないうちは設定に持たせない",
    file: "core.js", from: "    if (lpHasAny(lp)) out.lp = lp;", to: "    out.lp = lp;" },
  { name: "保存に失敗しても巻き戻さない", guards: "失敗したら元の値へ完全に戻す",
    file: "index.html", from: "    state.settings = before;\n    toast(L(\"保存できませんでした\",\"Could not save\"));", to: '    toast("保存できませんでした");' },
  { name: "内訳へ移るときに書きかけを捨てる", guards: "せっていの書きかけを取りこぼさない",
    file: "index.html", from: "    saveSettingsQuiet();                       // 書きかけの設定を取りこぼさない", to: "" },
  { name: "確かめずに行を消す", guards: "消す前に確かめる",
    file: "index.html", from: "  if(typeof confirm===\"function\" && !confirm(L(`「${target.name||\"（名前なし）\"}」を消しますか？`, `Delete \"${target.name||\"Unnamed\"}\"?`))) return;", to: "" },

  /* ---- 日記の日付えらび・写真ボタン ---- */
  { name: "書きかけを確かめずに捨てる", guards: "日付を変える前に確かめる",
    file: "index.html", from: "  if(dirty && typeof confirm===\"function\" && !confirm(L(\"書きかけの内容は保存されません。日付を変えますか？\",\"What you've written won't be saved. Change the date anyway?\"))){",
    to: "  if(false){" },
  { name: "おかしな日付でも切り替える", guards: "存在しない日付は受け付けない",
    file: "index.html", from: "  if(!Core.validateDateString(value)){ toast(L(\"日付を選んでください\",\"Please choose a date\")); return; }", to: "" },
  { name: "今日を選んでも今日に戻らない", guards: "今日を選んだら今日の日記へ戻る",
    file: "index.html", from: '  diaryEditDate = (value === todayISO()) ? null : value;', to: "  diaryEditDate = value;" },
  { name: "日付えらびを受け取らない", guards: "日付を選んだら切り替わる",
    file: "index.html", from: '  if(el && el.id === "d-date") pickDiaryDate(el.value);', to: "" },
  { name: "写真ボタンをただの文字に戻す", guards: "押せる場所だと分かる見た目",
    file: "index.html", from: '    : `<button class="photobtn" data-act="add-diary-photo">',
    to: '    : `<button class="btn-quiet" data-act="add-diary-photo">' },

  /* ---- いま見ている画面の印（下のタブ） ---- */
  { name: "いる画面の台の色を消す", guards: "いま見ている画面が色つきの台で分かる",
    file: "index.html", from: "  .nav button.on{color:var(--green-dd);font-weight:800;background:var(--green-l);",
    to: "  .nav button.on{color:var(--green-dd);font-weight:800;" },
  { name: "いる画面の絵文字を大きくしない", guards: "色だけに頼らず大きさでも分かる",
    file: "index.html", from: "  .nav button.on .ni{transform:scale(1.14)}", to: "" },
  { name: "いない画面の印を消し忘れる", guards: "前にいた画面の印を残さない",
    file: "index.html", from: "  else if(typeof btn.removeAttribute===\"function\") btn.removeAttribute(\"aria-current\");", to: "" },
  { name: "画面を切り替えても印を付け替えない", guards: "描き直しでタブの印を付け替える",
    file: "index.html", from: '  document.querySelectorAll("#nav button").forEach(b=>navMark(b, b.dataset.nav===view));',
    to: "" },

  { name: "開始日を経過日数の近似で出す", guards: "その年齢になる日を暦で出す",
    file: "core.js", from: "    const add = Math.ceil((a - whole) * days - 1e-9);",
    to: "    const add = Math.round((a - whole) * 365.2425);" },
  { name: "開始日を切り捨てる（まだ達していない日を返す）", guards: "その年齢に達する最初の日",
    file: "core.js", from: "    const add = Math.ceil((a - whole) * days - 1e-9);",
    to: "    const add = Math.floor((a - whole) * days);" },
  { name: "開始日で満年の分を進めない", guards: "開始日はその年齢の誕生日",
    file: "core.js", from: "    const from = anniversaryUTC(by, bm, bd, whole);\n    const to = anniversaryUTC(by, bm, bd, whole + 1);\n    const days = (to - from) / 864e5;",
    to: "    const from = anniversaryUTC(by, bm, bd, 0);\n    const to = anniversaryUTC(by, bm, bd, 1);\n    const days = (to - from) / 864e5;" },

  { name: "生年月日なしで入力内訳ではなく旧NISA月額へ戻す", guards: "生年月日なしでもNISA入力額を使う",
    file: "core.js", from: "    if (!nisaAuto(s)) return nisaManualMonthly(s);", to: "    if (!nisaAuto(s)) return num(s.nisaMonthly);" },
  { name: "書き出しでコピーを試さない", guards: "iPhoneでも書き出せる",
    file: "index.html", from: "    if(navigator.clipboard && navigator.clipboard.writeText){\n      navigator.clipboard.writeText(text).then(()=>toast(doneMsg), toFile);",
    to: "    if(false){\n      navigator.clipboard.writeText(text).then(()=>toast(doneMsg), toFile);" },
  { name: "コピーに失敗してもファイルへ落とさない", guards: "どちらかで必ず書き出せる",
    file: "index.html", from: "      navigator.clipboard.writeText(text).then(()=>toast(doneMsg), toFile);",
    to: "      navigator.clipboard.writeText(text).then(()=>toast(doneMsg));" },

  { name: "バックアップで共有シートを試さない", guards: "iPhoneでもファイルとして残せる",
    file: "index.html", from: "    if(navigator.share && navigator.canShare && typeof File === \"function\"){",
    to: "    if(false){" },
  { name: "共有を取り消してもダウンロードへ落とさない", guards: "どちらかで必ず書き出せる",
    file: "index.html", from: "          .then(()=>toast(doneMsg), toDownload);     // 取り消し・失敗ならダウンロードへ",
    to: "          .then(()=>toast(doneMsg));" },
  { name: "バックアップをコピーだけにする（ファイルで戻せない）", guards: "バックアップはファイルで残す",
    file: "index.html", from: "  saveFile(`kakeibo-backup-${todayISO()}.json`,",
    to: "  shareText(`kakeibo-backup-${todayISO()}.json`," },

  { name: "打っても自動で保存しない", guards: "保存ボタンを押さなくても消えない",
    file: "index.html", from: "  autoSave(el.id);",
    to: "  /* autoSave removed */" },
  { name: "内訳の自動保存だけやめる", guards: "内訳もその場で保存される",
    file: "index.html", from: '  if(view==="lp"){ lpSave(lpReadCurrent()); lpRefreshTotals(); }',
    to: '  if(false){ lpSave(lpReadCurrent()); lpRefreshTotals(); }' },
  { name: "せっていの自動保存だけやめる", guards: "せっていもその場で保存される",
    file: "index.html", from: '  if(view==="settings"){ saveSettingField(id); return; }',
    to: '  if(false){ saveSettingField(id); return; }' },
  { name: "自動保存で全部の欄を読み直す（生年月日が消える）", guards: "打った欄だけ書き換える",
    file: "index.html", from: '  if(view==="settings"){ saveSettingField(id); return; }',
    to: '  if(view==="settings"){ saveSettingsQuiet(); return; }' },
  { name: "NISAのタイルだけ色を変える", guards: "先取りのタイルは同じ見た目",
    file: "index.html", from: '  const nisaTile = `<button class="ds" data-act="lp-open" data-kind="nisa">',
    to: '  const nisaTile = `<button class="ds blue" data-act="lp-open" data-kind="nisa">' },
  { name: "自動保存で画面を作り直す（入力中の欄から指が外れる）", guards: "打っている間は作り直さない",
    file: "index.html", from: "function autoSave(id){", to: "function autoSave(id){ render();" },
  { name: "NISAの見出しを分かりにくい言い方に戻す", guards: "見出しは「積立」とだけ書く",
    file: "index.html", from: '${box(L("つみたて投資枠（積立）","Regular contributions")', to: '${box(L("つみたて投資枠：区間ごとの銘柄","Regular contributions by age range")' },

  { name: "銘柄を足しても入力欄へ移らない", guards: "足した欄まで画面が移る",
    file: "index.html", from: '  if(lpSave(a)){ render(); focusField(`${key==="tsumitateSchedule"?"lp-ts":"lp-gs"}-fn-${i}-${n}`); }',
    to: "  if(lpSave(a)){ render(); }" },
  { name: "区間を足しても入力欄へ移らない", guards: "足した区間まで画面が移る",
    file: "index.html", from: "    if(lpSave(a0)){ render(); focusField(id); }",
    to: "    if(lpSave(a0)){ render(); }" },
  { name: "行を足しても入力欄へ移らない", guards: "足した行まで画面が移る",
    file: "index.html", from: "  if(lpSave(a)){ render(); focusField(id); }",
    to: "  if(lpSave(a)){ render(); }" },
  { name: "足した行ではなく先頭の欄へ移る", guards: "足した行そのものへ移る",
    file: "index.html", from: "  const i = a[key3].length - 1;", to: "  const i = 0;" },

  /* ---- 画面の決めごと ---- */
  { name: "内訳のカードを入口カードと同じ名前に戻す", guards: "内訳の入力が縦に潰れない",
    file: "index.html", from: "  .lpseg{display:block;border:1px solid var(--line2)",
    to: "  .lpseg{border:1px solid var(--line2)" },
  { name: "目標タイルの色分けをやめる", guards: "目標と先取りを見分けられる",
    file: "index.html", from: '? `<button class="ds goal" data-go="settings" data-focus="f-gcur">',
    to: '? `<button class="ds" data-go="settings" data-focus="f-gcur">' },
  { name: "先取りタイルの文言を戻す", guards: "先取りは固定金額を入れる場所だと分かる",
    file: "index.html", from: '<div class="dv mono">${value}</div><div class="tapin">${T("home.tapin")}</div>',
    to: '<div class="dv mono">${value}</div><div class="tapin">タップで入力</div>' },
  { name: "初期化のたずねを一度だけにする", guards: "取り返しのつかない操作は二度たずねる",
    file: "index.html", from: "  if(!confirm(L(\"本当に、すべて消して最初から始めますか？\",\"Are you sure you want to erase everything and start over?\"))) return;",
    to: '  if(false) return;' },
  { name: "初期化に失敗しても元へ戻さない", guards: "保存できなければデータはそのまま",
    file: "index.html", from: "    state = before;                                 // 消える前へ完全に戻す",
    to: "    /* 戻さない */" },

  /* ---- 年齢の境目（誕生日ちょうど） ---- */
  { name: "年齢を経過日数の近似に戻す", guards: "誕生日ちょうどはきっちり整数",
    file: "core.js", from: "    return years + (nt - from) / span;",
    to: "    return (nt - bt) / (365.2425 * 24 * 3600 * 1000);" },
  { name: "応当日を末日へ寄せない（2月29日生まれ）", guards: "2月29日生まれの扱い",
    file: "core.js", from: "    return Date.UTC(y, bm - 1, Math.min(bd, lastDayOfMonth(y, bm)));",
    to: "    return Date.UTC(y, bm - 1, bd);" },
  { name: "満年数を1つ多く数える", guards: "誕生日の前日はまだ年をとらない",
    file: "core.js", from: "    if (anniversaryUTC(by, bm, bd, years) > nt) years -= 1;",
    to: "    if (false) years -= 1;" },

  /* ---- 横スワイプでの画面切り替え ---- */
  { name: "端でも回り込ませる", guards: "ホーム・心拍の端では行き止まりにする",
    file: "core.js", from: "    if (next < 0 || next >= SWIPE_VIEWS.length) return null;   // 端では動かさない",
    to: "    if (false) return null;   // 端では動かさない" },
  { name: "払う向きを逆にする", guards: "左へ払えば次、右へ払えば前",
    file: "core.js", from: "    const next = i + (Number(dx) < 0 ? 1 : -1); // 左へ払えば次、右へ払えば前",
    to: "    const next = i + (Number(dx) < 0 ? -1 : 1); // 左へ払えば次、右へ払えば前" },
  { name: "せっていもスワイプの並びに入れる", guards: "せっていは右上のボタン専用",
    file: "core.js", from: '  const SWIPE_VIEWS = ["home", "summary", "calendar", "diary", "health", "calc", "pulse"];',
    to: '  const SWIPE_VIEWS = ["home", "summary", "calendar", "diary", "health", "calc", "pulse", "settings"];' },
  { name: "縦スクロールでも切り替える", guards: "縦の動きと取り違えない",
    file: "index.html", from: "  if(Math.abs(dx) < Math.abs(dy) * 1.5) return null;   // 縦スクロールと取り違えない",
    to: "  if(false) return null;   // 縦スクロールと取り違えない" },
  { name: "ほんの少し触れただけで切り替える", guards: "60px以上動かしたときだけ切り替える",
    file: "index.html", from: "const SWIPE_MIN_X = 60;", to: "const SWIPE_MIN_X = 2;" },
  { name: "ゆっくりなぞっても切り替える", guards: "ゆっくりした動きでは切り替えない",
    file: "index.html", from: "  if(ms > SWIPE_MAX_MS) return null;", to: "  if(false) return null;" },
  { name: "シートを開いていても切り替える", guards: "記録シート中は切り替えない",
    file: "index.html", from: "  if(sheetState) return true;                       // 記録シートを開いている", to: "" },
  { name: "測定中でも切り替える", guards: "心拍の測定中は切り替えない",
    file: "index.html", from: "  if(pRunning) return true;                         // 心拍を測っている最中", to: "" },
  { name: "つまむ操作でも切り替える", guards: "2本指では切り替えない",
    file: "index.html", from: "  if(!e.touches || e.touches.length!==1) return;      // つまむ操作は対象外",
    to: "  if(!e.touches) return;      // つまむ操作は対象外" },

  /* ---- 心拍数（カメラ/PPG・β版） ---- */
  { name: "採用窓の下限を外す", guards: "採用窓6/9未満は保存しない",
    file: "core.js", from: "    minKept: 6,             // 採用窓 6/9 以上", to: "    minKept: 0,             // 採用窓 6/9 以上" },
  { name: "fpsの下限を外す", guards: "25fps未満は保存しない",
    file: "core.js", from: "    minFps: 25,             // 25fps 以上", to: "    minFps: 0,             // 25fps 以上" },
  { name: "測定品質の下限を下げる", guards: "★3未満は保存しない",
    file: "core.js", from: "    minStars: 3,            // 測定品質 ★3（普通）以上", to: "    minStars: 1,            // 測定品質 ★3（普通）以上" },
  { name: "指が離れた測定も保存する", guards: "途中で指が離れたら保存しない",
    file: "core.js", from: "    maxBadFrameRate: 0.15,  // 指が途中で離れていない", to: "    maxBadFrameRate: 1,  // 指が途中で離れていない" },
  { name: "保存できる心拍数の範囲を広げる", guards: "35〜200bpm の外は保存しない",
    file: "core.js", from: "    bpmMin: 35, bpmMax: 200,", to: "    bpmMin: 1, bpmMax: 400," },
  { name: "準備時間も計算に使う", guards: "最初の10秒は計算に使わない",
    file: "core.js", from: "return s && Number.isFinite(s.t) && s.t >= C.PREP_SEC * 1000;",
    to: "return s && Number.isFinite(s.t);" },
  { name: "途中で止めた測定も解析する", guards: "最後まで測れていない測定は確定しない",
    file: "core.js", from: "    if (use[use.length - 1].t < (C.TOTAL_SEC - 1) * 1000) {",
    to: "    if (false) {" },
  { name: "解析の長さを固定しない", guards: "窓の数がいつも9になる",
    file: "core.js", from: "    const sig = pulseResampleFixed(", to: "    const sig = pulseResample(" },
  { name: "移動平均の末尾を埋めない", guards: "最後の窓が壊れない",
    file: "core.js", from: "    for (let j = Math.max(1, n - half); j < n; j++) {", to: "    for (let j = n; j < n; j++) {" },
  { name: "履歴の上限を外す", guards: "心拍数の履歴は上限で頭打ちにする",
    file: "core.js", from: "    return out.length > PULSE_MAX ? out.slice(out.length - PULSE_MAX) : out;", to: "    return out;" },
  { name: "止めるときにライトを消さない", guards: "測定を止めたらライトも消す",
    file: "index.html", from: "  if(pTrack){ try{ pTrack.applyConstraints({advanced:[{torch:false}]}); }catch(e){} }   // ライトを必ず消す",
    to: "  if(pTrack){ /* 消さない */ }" },
  { name: "画面を移ってもカメラを止めない", guards: "心拍の画面を離れたら必ず止める",
    file: "index.html", from: "  if(view!==\"pulse\" && (pRunning || pStream || pGen!==pStopGen)) pulseStopAll();",
    to: "" },
  { name: "心拍の保存に失敗しても巻き戻さない", guards: "保存できなければ履歴を増やさない",
    file: "index.html", from: "  if(!save()){ state.pulse=before; return false; }", to: "  if(!save()){ return false; }" },
  { name: "心拍の削除に失敗しても巻き戻さない", guards: "消せなければ元へ戻す",
    file: "index.html", from: "  if(!save()){ state.pulse=before; toast(L(\"削除できませんでした\",\"Could not delete it\")); return; }",
    to: '  if(!save()){ toast("削除できませんでした"); return; }' },
  { name: "健康記録へ入れて失敗しても巻き戻さない", guards: "入れられなければ元へ戻す",
    file: "index.html", from: "    state.health=before;     // 入れる前へ完全に戻す", to: "" },

  { name: "拡大枠を効かなくする", guards: "枠3種の座標計算",
    file: "core.js", from: '{ key: "wide",  pad: 0.05 }', to: '{ key: "wide",  pad: 0.00 }' },
  { name: "縮小枠を効かなくする", guards: "枠3種の座標計算",
    file: "core.js", from: '{ key: "tight", pad: -0.10 }', to: '{ key: "tight", pad: 0.00 }' },
  { name: "枠のはみ出し防止を外す", guards: "画像範囲を超えない",
    file: "core.js", from: "if (x + w > 1) { w = 1 - x; }", to: "if (false) { w = 1 - x; }" },
  { name: "一致回数の加点を消す", guards: "同じ金額が複数回出たら点数が上がる",
    file: "core.js", from: "s += Math.min(30, Math.max(0, (Number(c.agree) || 1) - 1) * 15);", to: "s += 0;" },
  { name: "桁区切りの検査を外す", guards: "不自然な桁区切りは低評価",
    file: "core.js", from: "if (commaScore(c.raw) === 0) return 0;", to: "if (false) return 0;" },
  { name: "低確信でも自動確定する", guards: "低確信度なら候補選択",
    file: "core.js", from: "if (ranked[0].score < SCORE_CONFIRM) return true;", to: "if (false) return true;" },
  { name: "1位2位の点差を見ない", guards: "僅差なら候補選択",
    file: "core.js", from: "if (ranked.length > 1 && ranked[0].score - ranked[1].score < SCORE_GAP) return true;",
    to: "if (false) return true;" },
  { name: "1回出ただけで打ち切る", guards: "単独の高信頼では打ち切らない",
    file: "core.js", from: "if (votes[k] >= 2) return true;", to: "if (votes[k] >= 1) return true;" },
  { name: "自動反転をやめる", guards: "白抜き文字の反転",
    file: "core.js", from: "if (shouldInvert(data)) invertForOcr(data);", to: "if (false) invertForOcr(data);" },
  { name: "反転を二重に適用する", guards: "二重反転が起きない",
    file: "core.js", from: "if (shouldInvert(data)) invertForOcr(data);",
    to: "if (shouldInvert(data)) { invertForOcr(data); invertForOcr(data); }" },
  { name: "読み取り用の高解像度をやめる", guards: "高解像度画像の利用",
    file: "index.html", from: "const source = st.photoHi || st.photo;", to: "const source = st.photo;" },
  { name: "読み取り後に高解像度を捨てる", guards: "再試行でも高解像度を維持",
    file: "index.html", from: "  }finally{\n    /* 高解像度画像はここでは解放しない。",
    to: "  }finally{\n    releaseOcrImage(st);\n    /* 高解像度画像はここでは解放しない。" },
  { name: "シートを閉じても解放しない", guards: "解放のタイミング",
    file: "index.html", from: "if(!on){ releaseOcrImage(sheetState);", to: "if(!on){ (function(){})(sheetState);" },
  { name: "記録に高解像度画像を混ぜる", guards: "保存データに含めない",
    file: "index.html", from: "  else state.tx.push(rec);",
    to: "  else { rec.photoHi=st.photoHi; state.tx.push(rec); }" },
  { name: "候補をタップしたら保存する", guards: "タップだけでは保存しない",
    file: "index.html", from: "sheetState.ocrChoices=null;\n    sheetState.ocrNote=L(\"金額を入れました。",
    to: "sheetState.ocrChoices=null; save();\n    sheetState.ocrNote=L(\"金額を入れました。" },
  { name: "保存前の写真縮小をやめる", guards: "容量オーバー対策",
    file: "index.html", from: "if(photo) photo = await resizeDataUrl(photo, Core.PHOTO_STORE_MAX, 0.6);", to: "" },
  { name: "保存の失敗を握りつぶす", guards: "保存の成否判定",
    file: "index.html", from: "    lastSaveError=e; return false;\n  }\n}", to: "    lastSaveError=e; return true;\n  }\n}" },
  { name: "スクリプト読み込み関数を消す", guards: "呼んでいる関数が実在するか",
    file: "index.html", from: "function loadScript(src){", to: "function loadScript_REMOVED(src){" },
  { name: "保存の成否が出る前に高解像度を解放する", guards: "記録確定時にだけ解放",
    file: "index.html", from: "  let photo = st.photo || null;", to: "  releaseOcrImage(st);\n  let photo = st.photo || null;" },
  { name: "保存に失敗しても高解像度を解放する", guards: "失敗時は維持する",
    file: "index.html", from: "  state.tx = JSON.parse(before);", to: "  releaseOcrImage(st);\n  state.tx = JSON.parse(before);" },
  { name: "写真を外した再保存の成功で解放しない", guards: "再保存成功時にも解放",
    file: "index.html", from: "      releaseOcrImage(st);          // 写真は諦めたが記録は確定した", to: "" },
  { name: "キャッシュの版数を上げ忘れる", guards: "更新が端末に届く",
    file: "sw.js", from: "const CACHE = \"kakeibo-v65\";",
    to: "const CACHE = \"kakeibo-v20\";" },
  { name: "設定の保存失敗を巻き戻さない", guards: "設定保存の巻き戻し",
    file: "index.html", from: "  if(!save()) state.settings = before;        // 失敗したら元のまま",
    to: "  save();" },
  { name: "設定の保存失敗でも成功と表示する", guards: "失敗時に成功メッセージを出さない",
    file: "index.html", from: "    if(!save()){ state=before; toast(T(\"set.saveFailed\")); return; }",
    to: "    if(!save()){ state=before; toast(T(\"set.saved\")); }" },
  { name: "記録削除の失敗を巻き戻さない", guards: "記録削除の巻き戻し",
    file: "index.html", from: "    state.tx=beforeTx;\n    state.recordCalcHistory=beforeHistory;", to: "" },
  { name: "写真一括削除の失敗を巻き戻さない", guards: "写真削除の巻き戻し",
    file: "index.html", from: "    state = before;               // 記録写真も日記写真も完全に元へ戻す", to: "" },
  { name: "写真0枚でも保存を試みる", guards: "写真0枚なら保存しない",
    file: "index.html", from: "  if(!n){ toast(L(\"消せる写真はありません\",\"There are no photos to delete\")); return; }",
    to: '  if(!n){ }' },
  { name: "バックアップ復元の失敗を巻き戻さない", guards: "復元の巻き戻し",
    file: "index.html", from: "      state = before;                               // 保存できないなら元のまま", to: "" },
  { name: "バックアップの確認ダイアログを出さない", guards: "上書き前の確認",
    file: "index.html", from: "    if(!ok){ clear(); return; }                     // キャンセル：何も変えない", to: "" },
  { name: "壊れた記録をそのまま取り込む", guards: "記録の正規化",
    file: "core.js", from: "    if (!validateDateString(tx.date)) return null;            // 日付が不正なら捨てる", to: "" },
  { name: "巨大な金額を制限しない", guards: "金額の上限",
    file: "core.js", from: "    if (amount > max) amount = max;             // 巨大値は上限で止める",
    to: "" },
  { name: "危険な写真データを通す", guards: "写真は画像のdata URLだけ",
    file: "core.js", from: "    const photo = isPhotoDataUrl(tx.photo) ? tx.photo : null;",
    to: "    const photo = (typeof tx.photo === \"string\" && tx.photo) ? tx.photo : null;" },
  { name: "Tesseractの版を範囲指定に戻す", guards: "完全バージョン固定",
    file: "index.html", from: 'const TESSERACT_VERSION = "5.1.1";', to: 'const TESSERACT_VERSION = "5";' },
  { name: "旧固定費キーを支出カテゴリから外す", guards: "旧データの互換",
    file: "core.js", from: '    { k: "rent",     e: "🏠", n: "住居" },', to: "" },
  { name: "支出集計から一部カテゴリを除外する", guards: "二重計上・計算漏れなし",
    file: "core.js", from: "    const spendTotal = sum(expRecs, function (t) { return t.amount; }) + lpSpendSum;",
    to: "    const spendTotal = sum(expRecs.filter(function(t){return t.cat!=='rent';}), function (t) { return t.amount; }) + lpSpendSum;" },
  { name: "健康の範囲外を受け入れる", guards: "健康記録の正規化",
    file: "core.js", from: "      if (v < f.min || v > f.max) return;              // 範囲外は捨てる", to: "" },
  { name: "健康の未入力を0として記録する", guards: "未入力は記録しない",
    file: "core.js", from: '      if (raw === "" || raw === null || raw === undefined) return;  // 未入力はその項目を入れない', to: "" },
  { name: "健康の保存失敗を巻き戻さない", guards: "健康保存の巻き戻し",
    file: "index.html", from: "    state.health=before;      // 失敗したら完全に戻す", to: "" },
  { name: "バックアップから健康を外す", guards: "健康もバックアップに含む",
    file: "core.js", from: "      health: normalizeHealth(st.health),\n", to: "" },
  { name: "日記の空を残す", guards: "空の日記は残さない",
    file: "core.js", from: '    if (text.trim() === "" && !photo) return null;', to: "" },
  { name: "日記の上限を外す", guards: "長すぎる本文を切る",
    file: "core.js", from: "    text = text.slice(0, DIARY_MAX);", to: "" },
  { name: "日記の危険な写真を通す", guards: "写真は画像data URLだけ",
    file: "core.js", from: "      if (isPhotoDataUrl(raw.photo)) photo = raw.photo;",
    to: "      if (typeof raw.photo === \"string\" && raw.photo) photo = raw.photo;" },
  { name: "日記の写真を保存前に縮小しない", guards: "容量対策",
    file: "index.html", from: "  if(photo && diaryPhotoPending) photo = await resizeDataUrl(photo, Core.PHOTO_STORE_MAX, 0.6);", to: "" },
  { name: "日記の保存失敗を巻き戻さない", guards: "日記保存の巻き戻し",
    file: "index.html", from: "  state.diary=before;   // それでも駄目なら完全に戻す", to: "" },
  { name: "バックアップから日記を外す", guards: "日記もバックアップに含む",
    file: "core.js", from: "      diary: normalizeDiary(st.diary),", to: "" },
  { name: "その日以外の記録も混ぜる", guards: "カレンダーの日別集約",
    file: "core.js", from: "    const txs = mine.filter(function (t) { return t && t.date === date; });",
    to: "    const txs = mine;" },
  { name: "別の月にも印をつける", guards: "月ごとの印つけ",
    file: "core.js", from: "if (t && typeof t.date === \"string\" && t.date.slice(0, 7) === ym) {",
    to: "if (t && typeof t.date === \"string\") {" },
  { name: "のこりのマイナスを0にしない", guards: "使いすぎでものこりは0",
    file: "core.js", from: "    const remain = Math.max(0, income - spend - setAside);   // のこり（マイナスは0扱い）",
    to: "    const remain = income - spend - setAside;" },
  { name: "円グラフの割合を収入基準にしない", guards: "収入を100%とした割合",
    file: "core.js", from: "    const base = income > 0 ? income : (spend + setAside);   // 収入0なら支出+先取りを基準に",
    to: "    const base = spend + setAside;" },
  { name: "内訳を一部カテゴリだけにする", guards: "全カテゴリの内訳",
    file: "core.js", from: "    expRecs.forEach(function (t) {\n      byCat[t.cat] = (byCat[t.cat] || 0) + num(t.amount);\n    });",
    to: "    expRecs.filter(function(t){return t.cat!=='rent';}).forEach(function (t) {\n      byCat[t.cat] = (byCat[t.cat] || 0) + num(t.amount);\n    });" },
  { name: "core.js をキャッシュ優先に戻す", guards: "更新直後に古いcore.jsを出さない",
    file: "sw.js", from: "  if (isAppCode(url)) {", to: "  if (false) {" },
  { name: "sw.js をブラウザのキャッシュ任せにする", guards: "sw.js を必ず取り直す",
    file: "index.html", from: '        updateViaCache: "none"', to: '        updateViaCache: "imports"' },
  { name: "更新確認をやめる", guards: "登録後の update()",
    file: "index.html", from: "      await registration.update();", to: "" },
  { name: "初回登録でも読み直す（余計なリロード）", guards: "初回登録では読み直さない",
    file: "index.html", from: "        if (!hadController) return;  // ← 初回登録。更新ではないので読み直さない", to: "" },
  { name: "制御の有無を見ない（常に更新扱い）", guards: "初回登録と更新の区別",
    file: "index.html", from: "      const hadController = !!navigator.serviceWorker.controller;",
    to: "      const hadController = true;" },
  { name: "再読み込みの印を外す（無限ループ）", guards: "無限再読み込みが起きない",
    file: "index.html", from: "        if (refreshing) return;      // ← 無限に読み直さないための印", to: "" },
  { name: "切り替わっても読み直さない", guards: "新しい版が画面に反映される",
    file: "index.html", from: "        window.location.reload();", to: "" },
  { name: "古いキャッシュを消さない", guards: "古いアプリが残らない",
    file: "sw.js", from: "keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))",
    to: "keys.filter((k) => false).map((k) => caches.delete(k))" },
  { name: "画面をキャッシュ優先に戻す", guards: "画面はネットワーク優先",
    file: "sw.js", from: "  if (isNavigation(e.request, url)) {", to: "  if (false) {" },
  { name: "桁欠けに気づかない", guards: "先頭の桁が欠けた読み取りの補正",
    file: "core.js", from: "    if (/[,.]\\s*$/.test(pre)) return { digits: null, evidence: \"comma\" };",
    to: "    if (false) return { digits: null, evidence: \"comma\" };" },
  { name: "桁欠けの減点をやめる", guards: "合計らしい候補を上に",
    file: "core.js", from: "    if (c.truncated) s -= 40;", to: "    if (c.truncated) s -= 0;" },
  { name: "推測を自動入力する", guards: "推測は必ず選んでもらう",
    file: "core.js", from: '    if (ranked[0].source === "reconstructed") return true;',
    to: "    if (false) return true;" },
  { name: "推測の信頼度に上限を設けない", guards: "直接読めた候補と区別する",
    file: "core.js", from: "      confidence: Math.min(RECON_MAX_CONF, Number(o.confidence) || 0),",
    to: "      confidence: Number(o.confidence) || 0," },
  { name: "補正の対象を広げすぎる（候補が増えすぎる）", guards: "3桁のときだけ補正する",
    file: "core.js", from: "    if (d.amount < 100 || d.amount > 999) return null;        // 3桁のときだけ",
    to: "    if (false) return null;        // 3桁のときだけ" },
  /* ---- 毎月固定の印・選べるカテゴリ ---- */
  { name: "📦 を選べるボタンに戻す", guards: "「その他」は1つだけ",
    file: "core.js", from: "  const EXP_PICK_CATS = EXP_CATS.filter(function (c) { return !c.hidden; });",
    to: "  const EXP_PICK_CATS = EXP_CATS;" },
  { name: "📦 のキーごと消す", guards: "過去の記録が消えない",
    file: "core.js", from: '    { k: "fixother", e: "📦", n: "その他", hidden: true },\n', to: "" },
  { name: "毎月固定の印を見ない", guards: "固定とそれ以外の切り分け",
    file: "core.js", from: '    return !!(t && t.type === "expense" && t.recurring === true);', to: "    return false;" },
  { name: "収入にも固定の印を認める", guards: "印は支出だけ",
    file: "core.js", from: '    return !!(t && t.type === "expense" && t.recurring === true);',
    to: "    return !!(t && t.recurring === true);" },
  { name: "印を文字列でも受け入れる", guards: "印は true のときだけ",
    file: "core.js", from: '    const recurring = type === "expense" && tx.recurring === true;',
    to: '    const recurring = type === "expense" && !!tx.recurring;' },
  { name: "毎月固定も日割りする", guards: "固定は日割りしない",
    file: "core.js", from: "      ? recurringSoFar + Math.round((spotSoFar / elapsed) * days) : 0;",
    to: "      ? Math.round((spentSoFar / elapsed) * days) : 0;" },
  { name: "まだ来ていない日付もペースに混ぜる", guards: "経過日数までで見る",
    file: "core.js", from: "    const spotSoFar = spentSoFar - recurringSoFar;", to: "    const spotSoFar = c.spotSpend;" },
  { name: "毎月固定を、印を見ずに0にする", guards: "印のとおりに分かれる",
    file: "core.js", from: "    const recurringSpend = ", to: "    const recurringSpend = 0 * " },
  { name: "保存のときに印を落とす", guards: "オンで記録したら残る",
    file: "index.html", from: "  if(recurring) rec.recurring=true;   // オフのときはキーごと持たない（保存を軽くする）\n",
    to: "" },
  /* 旧「更新のときに印を消さない」は、ここから外した。
     第1段階で編集の経路を書き換えた結果、当たり先だった1行
     （計算コアが落としたキーを rec からも消す）が **到達不能** になったため。
     rec に付くキーは id/type/amount/cat/date/memo/photo と、
     支出のときだけの recurring、JP以外のときだけの country。
     どれも normalizeTransaction が落とさないので、消すキーは存在しない。
     （型と国の全組み合わせで確かめてある）
     印を落とす振る舞いそのものは「収入に切り替えても印を残す」が見張っている。
     あの1行は将来の書き換えに備えた保険として残す。 */
  { name: "直しても記録に反映されない", guards: "直した内容が記録に反映される",
    file: "index.html", from: "  if(st.mode===\"edit\"){ if(idx>=0) state.tx[idx]=rec; }",
    to: "  if(st.mode===\"edit\"){ }" },
  { name: "収入に切り替えても印を残す", guards: "収入に固定費の印を付けない",
    file: "index.html", from: '  const recurring = st.type==="expense" && st.recurring===true;',
    to: "  const recurring = st.recurring===true;" },
  { name: "スイッチを押しても切り替わらない", guards: "毎月固定の切り替え",
    file: "index.html", from: "sheetState.recurring=!sheetState.recurring;", to: "sheetState.recurring=sheetState.recurring;" },
  /* ---- 詳細分析（分析タブ） ---- */
  { name: "月末の予測を経過日数で割らない", guards: "つかうペースの予測",
    file: "core.js", from: "      ? recurringSoFar + Math.round((spotSoFar / elapsed) * days) : 0;",
    to: "      ? spentSoFar : 0;" },
  { name: "つかってよい額から先取りを引かない", guards: "予算＝収入－先取り",
    file: "core.js", from: "    const budget = c.incomeTotal - c.setAside;", to: "    const budget = c.incomeTotal;" },
  { name: "収入が無くても使いすぎと決めつける", guards: "未記録なら判定しない",
    file: "core.js", from: "      over: c.hasIncome ? forecast - budget : null,", to: "      over: forecast - budget," },
  { name: "つかわなかった日を数えない", guards: "つかった日／つかわなかった日",
    file: "core.js", from: "      if (perDayAmount[d] > 0) spendDays += 1; else noSpend += 1;", to: "      spendDays += 1;" },
  { name: "カテゴリ集計にほかの月を混ぜる", guards: "当月だけを数える",
    file: "core.js", from: "      if (!t || t.type !== \"expense\" || cycleOf(t.date, startDay) !== ym) return;\n      out[t.cat] = (out[t.cat] || 0) + num(t.amount);",
    to: "      if (!t || t.type !== \"expense\") return;\n      out[t.cat] = (out[t.cat] || 0) + num(t.amount);" },
  { name: "曜日の集計にほかの月を混ぜる", guards: "曜日ぐせは当月だけ",
    file: "core.js", from: "      if (!t || t.type !== \"expense\" || cycleOf(t.date, startDay) !== ym) return;\n      if (!validateDateString(t.date)) return;",
    to: "      if (!t || t.type !== \"expense\") return;\n      if (!validateDateString(t.date)) return;" },
  { name: "先月ではなく当月と比べる", guards: "先月との比較",
    file: "core.js", from: "    const prev = categorySpend(txs, shiftYm(ym, -1), startDay);", to: "    const prev = categorySpend(txs, ym, startDay);" },
  { name: "平均を記録の無い月でも割る", guards: "平均は記録のあった月だけ",
    file: "core.js", from: "        avg: activeMonths > 0 ? Math.round(sumPast / activeMonths) : null,",
    to: "        avg: Math.round(sumPast / past.length)," },
  { name: "使いすぎの警告を出さない", guards: "予算を超えそうなら知らせる",
    file: "core.js", from: "      if (pace.over > 0) {", to: "      if (false) {" },
  { name: "先月の記録が無くても「ふえた」と言う", guards: "はじめての項目は増加にしない",
    file: "core.js", from: "    if (up && up.diff > 0 && up.prev > 0) {", to: "    if (up && up.diff > 0) {" },
  { name: "気づきを何件でも出す", guards: "気づきは5件まで",
    file: "core.js", from: "    return out.slice(0, 5);", to: "    return out;" },
  { name: "分析タブを開いても今月のまとめを出す", guards: "タブの切り替え",
    file: "index.html", from: 'sumTab==="analysis" ? renderAnalysis() : renderSummary();', to: "renderSummary();" },
  /* ---- 先月の🔁をまとめて入れる ---- */
  { name: "今月にすでにあっても、もう一度入れる", guards: "二重計上を防ぐ",
    file: "core.js", from: "      const already = (done[t.cat] || 0) > 0;", to: "      const already = false;" },
  { name: "先月ではなく当月を写す", guards: "写すのは先月の記録",
    file: "core.js", from: "      return isRecurring(t) && cycleOf(t.date, startDay) === prevYm;",
    to: "      return isRecurring(t) && cycleOf(t.date, startDay) === ym;" },
  { name: "印の無い支出まで写す", guards: "🔁が付いたものだけ",
    file: "core.js", from: "      return isRecurring(t) && cycleOf(t.date, startDay) === prevYm;",
    to: "      return t.type === \"expense\" && cycleOf(t.date, startDay) === prevYm;" },
  { name: "無い起点日を月末へ寄せない（2/31）", guards: "月末へ丸める",
    file: "core.js", from: "    return Math.min(normalizeCycleStart(startDay), daysInMonth(ym));",
    to: "    return normalizeCycleStart(startDay);" },
  { name: "区切りからはみ出す日付を作る", guards: "写す日付は区切りの中",
    file: "core.js", from: "    if (iso > r.to) iso = r.to;", to: "" },
  { name: "区切りの境目を1日ずらす", guards: "給料日当日はその月から",
    file: "core.js", from: "    return Number(String(iso).slice(8, 10)) >= cycleStartDay(ym, s) ? ym : shiftYm(ym, -1);",
    to: "    return Number(String(iso).slice(8, 10)) > cycleStartDay(ym, s) ? ym : shiftYm(ym, -1);" },
  { name: "集計が区切りを見ずに暦の月で数える", guards: "給料日起点の集計",
    file: "core.js", from: "    const month = all.filter(function (t) { return cycleOf(t.date, s.cycleStart) === ym; });",
    to: "    const month = all.filter(function (t) { return monthOf(t.date) === ym; });" },
  { name: "写した記録に🔁を付けない", guards: "写した先も毎月固定",
    file: "index.html", from: 'state.tx.push({id:uid(),type:"expense",amount:i.amount,cat:i.cat,date:i.date,memo:i.memo,photo:null,recurring:true});',
    to: 'state.tx.push({id:uid(),type:"expense",amount:i.amount,cat:i.cat,date:i.date,memo:i.memo,photo:null});' },
  { name: "確認しないで入れる", guards: "入れる前に確認する",
    file: "index.html", from: "  if(!ok) return;                                   // キャンセル：何も変えない", to: "" },
  { name: "まとめて入れる失敗を巻き戻さない", guards: "失敗したら1件も増やさない",
    file: "index.html", from: "    state.tx = before;            // 途中まで増えた状態を残さない", to: "" },
  /* ---- 今日やることカード ---- */
  { name: "やることを何件でも出す", guards: "多くても2件",
    file: "core.js", from: "    return out.slice(0, TASK_MAX);", to: "    return out;" },
  { name: "給料日より前でも催促する", guards: "給料日を過ぎてから",
    file: "core.js", from: "      if (hint !== null && today >= dateInCycle(ym, startDay, hint)) {", to: "      if (true) {" },
  { name: "はじめての人にも給料を催促する", guards: "履歴が無ければ催促しない",
    file: "core.js", from: "      if (hint !== null && today >= dateInCycle(ym, startDay, hint)) {",
    to: "      if (today >= dateInCycle(ym, startDay, hint === null ? 1 : hint)) {" },
  { name: "1日あいただけで記録を催促する", guards: "とだえ日数のしきい値",
    file: "core.js", from: "      if (gap >= TASK_QUIET_DAYS) {", to: "      if (gap >= 1) {" },
  { name: "まだ来ていない記録も数える", guards: "未来の日付は数えない",
    file: "core.js", from: "      return t && t.type === \"expense\" && validateDateString(t.date) && t.date <= today;",
    to: "      return t && t.type === \"expense\" && validateDateString(t.date);" },
  { name: "続けていない人にも日記を催促する", guards: "習慣の人にだけ",
    file: "core.js", from: "    if (isHabit(st.diary, today) && !(st.diary || {})[today]) {",
    to: "    if (!(st.diary || {})[today]) {" },
  { name: "今日つけた分も習慣の数に入れる", guards: "今日を除いて数える",
    file: "core.js", from: "      if (d >= from && d < today) n += 1;", to: "      if (d >= from && d <= today) n += 1;" },
  { name: "やることが無くてもカードを出す", guards: "空のカードを出さない",
    file: "index.html", from: '  if(!tasks.length && !shown.length) return "";', to: "" },
  { name: "まとめのカードを横1列に戻す", guards: "カードがはみ出さない",
    file: "index.html", from: "  .sumcards{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}",
    to: "  .sumcards{display:flex;gap:10px}" },
  { name: "オフライン時の受け皿を外す", guards: "オフラインでも起動する",
    file: "sw.js", from: "        .then((hit) => hit || new Response(\"\", {",
    to: "        .then((hit) => hit || undefined || new Response(undefined && {" },
  { name: "済んだ予定もホームに出す", guards: "済んだらホームから消える",
    file: "core.js", from: "    return dayPlans(state, today).filter(function (p) { return !p.done; });",
    to: "    return dayPlans(state, today);" },
  { name: "時刻なしの予定を先頭に置く", guards: "時刻の早い順・時刻なしは最後",
    file: "core.js", from: '      const at = a.time || "99:99", bt = b.time || "99:99";',
    to: '      const at = a.time || "00:00", bt = b.time || "00:00";' },
  { name: "1日に入れられる予定の上限を外す", guards: "1日の件数に上限がある",
    file: "core.js", from: "        .slice(0, PLAN_PER_DAY_MAX)", to: "" },
  { name: "中身が空の予定も残す", guards: "空の予定は残さない",
    file: "core.js", from: '    if (text.trim() === "") return null;',
    to: '' },
  { name: "予定IDの長さ制限を外す", guards: "バックアップ由来の予定IDは64文字以内",
    file: "core.js", from: '    let id = raw.id == null ? "" : String(raw.id).slice(0, 64);',
    to: '    let id = raw.id == null ? "" : String(raw.id);' },
  { name: "重複した予定IDをそのまま残す", guards: "同じ日の予定IDは重複させない",
    file: "core.js", from: '          if (!seen[p.id]) { seen[p.id] = true; return p; }',
    to: '          return p;' },
  { name: "おかしな時刻をそのまま通す", guards: "時刻は24時間の範囲だけ",
    file: "core.js", from: '    if (h < 0 || h > 23 || mi < 0 || mi > 59) return "";', to: "" },
  { name: "保存に失敗しても予定を残す", guards: "保存失敗時の巻き戻し",
    file: "index.html", from: "  if(!save()){ state.plans=before; toast(L(\"予定を保存できませんでした\",\"Could not save the schedule\")); render(); return; }",
    to: "  save();" },
  { name: "ホームに今日の予定を全部出す", guards: "ホームに出すのは3件まで",
    file: "index.html", from: "  const shown=plans.slice(0, Core.PLAN_SHOW_MAX);", to: "  const shown=plans;" },

  /* --- 金額の電卓 --- */
  { name: "わり算を切り捨てにする", guards: "わり算は四捨五入して整数",
    file: "core.js", from: '    if (op === "/") return b === 0 ? null : Math.round((a / b) * s);',
    to: '    if (op === "/") return b === 0 ? null : Math.floor((a / b) * s);' },
  { name: "0で割れてしまう", guards: "0では割らない",
    file: "core.js", from: '    if (op === "/") return b === 0 ? null : Math.round((a / b) * s);',
    to: '    if (op === "/") return Math.round((a / b) * s);' },
  { name: "＝を押さないと計算されない", guards: "待っている計算を済ませて記録する",
    file: "core.js", from: "    if (c.op && c.acc !== null && c.cur !== \"\") {\n      const r = calcApply(c.acc, c.op, majorTextToMinorRound(c.cur, c.dec || 0), calcScale(c));\n      return r === null ? c.acc : r;\n    }",
    to: "" },
  { name: "打ち込める桁数の上限を外す", guards: "桁数に上限がある",
    file: "core.js", from: "    intPart = intPart.slice(0, CALC_DIGITS_MAX);", to: "    intPart = intPart;" },
  { name: "＝のあとに打ち足せてしまう", guards: "＝のあとは打ち直しになる",
    file: "core.js", from: '      if (c.done) { c.acc = null; c.op = ""; c.cur = ""; c.done = false; c.expr = ""; }\n      const next = c.cur === "0" ? k : c.cur + k;', to: '      const next = c.cur === "0" ? k : c.cur + k;' },
  { name: "式を出さない", guards: "打っている式が見える",
    file: "core.js", from: '      c.expr = calcFmt(c.acc, c) + " " + CALC_OP_LABEL[k];', to: '      c.expr = "";' },
  { name: "記録するとき、待っている計算を捨てる", guards: "＝を押し忘れても計算される",
    file: "index.html", from: '  if(st.calc && st.calc.op){ st.calc=Core.calcPress(st.calc,"="); st.amount=Core.calcDisplay(st.calc); }', to: "" },
  { name: "金額欄にキーボードを出す", guards: "アプリの電卓だけで打つ",
    file: "index.html", from: 'id="s-amt" readonly inputmode="none"', to: 'id="s-amt" inputmode="numeric"' },

  /* --- ホームの「今月の予定」 --- */
  { name: "ほかの月の予定まで混ぜる", guards: "今月の予定だけを出す",
    file: "core.js", from: "      if (!validateDateString(date) || monthOf(date) !== ym) return;\n      const list = dayPlans(st, date);",
    to: "      const list = dayPlans(st, date);" },
  { name: "のこり件数を全件にする", guards: "のこり件数の数えかた",
    file: "core.js", from: "    return { ym: ym, days: days, total: total, done: done, left: total - done };",
    to: "    return { ym: ym, days: days, total: total, done: done, left: total };" },
  { name: "ホームの一覧の行数の上限を外す", guards: "多すぎたら打ち切る",
    file: "index.html", from: "  const shownRows=rows.slice(0, Core.PLAN_HOME_MAX);", to: "  const shownRows=rows;" },
  { name: "予定が無くても今月の予定カードを出す", guards: "空のカードを出さない",
    file: "index.html", from: "  if(!m.total) return \"\";", to: "" },

  /* --- 関数電卓 --- */
  { name: "かけ算より足し算を先に計算する", guards: "計算の順番",
    file: "core.js", from: '    "*": { prec: 2, right: false },', to: '    "*": { prec: 1, right: false },' },
  { name: "べき乗を左から計算する", guards: "べき乗は右から",
    file: "core.js", from: '    "^": { prec: 4, right: true },', to: '    "^": { prec: 4, right: false },' },
  { name: "符号のマイナスをふつうの引き算にする", guards: "符号のマイナス",
    file: "core.js", from: "        if (unary) {\n          stack.push({ t: \"unary\", v: tk.v });\n          prev = { t: \"unary\" };\n          continue;\n        }",
    to: "" },
  { name: "かっこの数が合わなくても計算する", guards: "かっこが合っているか見る",
    file: "core.js", from: "        if (!found) return null;", to: "" },
  { name: "三角関数を、いつも弧度で計算する", guards: "はじめは度で計算する",
    file: "core.js", from: "    const a = deg ? (x * Math.PI) / 180 : x;", to: "    const a = x;" },
  { name: "電卓でも0で割れてしまう", guards: "0では割らない",
    file: "core.js", from: '        else if (tk.v === "/") { if (b === 0) return { divZero: true }; st.push(a / b); }',
    to: '        else if (tk.v === "/") { st.push(a / b); }' },
  { name: "答えが数でなくても出してしまう", guards: "計算できないものは出さない",
    file: "core.js", from: "    if (!Number.isFinite(r.value)) return { ok: false, error: \"計算できません\", errorKey: \"calc.notNum\" };", to: "" },
  { name: "小数や0以下でも家計簿にまわす", guards: "1円以上の整数だけ記録にまわす",
    file: "core.js", from: "    return n > 0 && Math.abs(v - n) < 1e-9 ? n : null;", to: "    return n;" },
  { name: "履歴を古い順にためる", guards: "新しい計算が上に出る",
    file: "core.js", from: "      s.history = [{ expr: sciExpr(s), value: r.value }].concat(s.history).slice(0, SCI_HISTORY_MAX);",
    to: "      s.history = s.history.concat([{ expr: sciExpr(s), value: r.value }]).slice(0, SCI_HISTORY_MAX);" },
  { name: "式の長さの上限を外す", guards: "式が長くなりすぎない",
    file: "core.js", from: "    if (s.tokens.length >= SCI_TOKENS_MAX) { s.error = \"式が長すぎます\"; s.errorKey = \"calc.tooLong\"; return s; }", to: "" },
  { name: "AC で履歴まで消す", guards: "ACでも履歴は残す",
    file: "core.js", from: "    if (k === \"AC\") { const keep = { ans: s.ans, deg: s.deg, history: s.history }; return Object.assign(newSci(), keep); }",
    to: "    if (k === \"AC\") return newSci();" },

  /* --- 下のタブを画面の下に固定する --- */
  { name: "下のタブを半透明のぼかしに戻す", guards: "iOSで途中に取り残されない",
    file: "index.html", from: "    padding-bottom:env(safe-area-inset-bottom,0px);background:var(--card);",
    to: "    padding-bottom:env(safe-area-inset-bottom,0px);background:rgba(255,255,255,.94);backdrop-filter:blur(8px);" },
  { name: "下のタブを独立した層にしない", guards: "iOSで途中に取り残されない",
    file: "index.html", from: "    transform:translateZ(0);-webkit-backface-visibility:hidden;backface-visibility:hidden;will-change:transform;\n    z-index:100}",
    to: "    z-index:100}" },
  { name: "下のタブより記録の画面を手前にする", guards: "タブが隠れない",
    file: "index.html", from: "    z-index:100}", to: "    z-index:40}" },
  { name: "画面の高さをアドレスバーに合わせない", guards: "高さの取りかた",
    file: "index.html", from: "  #app{max-width:520px;margin:0 auto;min-height:100vh;min-height:100dvh;",
    to: "  #app{max-width:520px;margin:0 auto;min-height:100vh;" },
  /* ---- 推移グラフの目もり・変化量 ---- */
  { name: "目もりを切りのよい数に合わせない", guards: "軸の数字が半端にならない",
    file: "core.js", from: "    const lo = round6(Math.floor(round6(min / step)) * step);",
    to: "    const lo = min;" },
  { name: "上の端を値より下にする", guards: "線がはみ出さない",
    file: "core.js", from: "    const hi = round6(Math.ceil(round6(max / step)) * step);",
    to: "    const hi = max - step;" },
  { name: "同じ値ばかりのときに余白を作らない", guards: "0で割らない",
    file: "core.js", from: "      const pad = Math.max(Math.abs(min) * 0.02, 0.5);", to: "      const pad = 0;" },
  { name: "日付ラベルの最初と最後を落とす", guards: "最初と最後は必ず出す",
    file: "core.js", from: "      const v = Math.round((i * (n - 1)) / (m - 1));", to: "      const v = i + 1;" },
  { name: "変化量の丸めをやめる", guards: "小数の誤差を出さない",
    file: "core.js", from: "      diff: round6(b.value - a.value),", to: "      diff: b.value - a.value," },
  /* ---- 確定ボタンの見た目 ---- */
  { name: "確定ボタンの色を消す", guards: "ボタンだと分かる見た目",
    file: "index.html", from: "    background:var(--green-d);color:#fff;border-radius:15px;padding:16px 14px;",
    to: "    border-radius:15px;padding:16px 14px;" },
  { name: "確定ボタンを小さくする", guards: "指で押しやすい大きさ",
    file: "index.html", from: "    font-size:16px;font-weight:800;line-height:1.35;text-align:center;",
    to: "    font-size:12px;font-weight:800;line-height:1.35;text-align:center;" },
  { name: "電卓の ＝ を他のキーと同じ大きさにする", guards: "＝ がいちばん目立つ",
    file: "index.html", from: "  .scieq{margin-top:10px;min-height:66px;font-size:30px;letter-spacing:.1em;",
    to: "  .scieq{margin-top:10px;min-height:52px;font-size:19px;letter-spacing:.1em;" },
  /* ---- バックアップに予定を含める ---- */
  { name: "復元で予定を入れ忘れる", guards: "予定も復元される",
    file: "index.html", from: "    state.plans = restored.plans || {};   // 予定も復元する（入れ忘れると古い予定が残る）",
    to: "" },
  /* ---- つかうペースの目もり・凡例 ---- */
  { name: "ペースの目もりを勝手な式にする", guards: "目もりは core の計算",
    file: "index.html", from: "  const sc=Core.chartScale([0, last.cum, p.budget>0?p.budget:0, showFore?p.forecast:0], Core.CHART_TICKS);",
    to: "  const sc={lo:0,hi:Math.max(last.cum,p.budget,p.forecast,1),step:1,ticks:[]};" },
  { name: "金額を万単位で書かない", guards: "目もりの読みやすさ",
    file: "index.html", from: '  if(v>=10000){ return tickShort(v/10000)+"万"; }',
    to: "" },
  { name: "凡例から予測の線を消す", guards: "どの線か分かる凡例",
    file: "index.html", from: '    ${showFore?`<span>${sw(col,"3 3")} ${T("an.forecastLine")}</span>`:""}',
    to: "" },
  /* ---- 心拍数 ---- */
  { name: "心拍数の項目を消す", guards: "心拍数を記録できる",
    file: "core.js", from: '    { k: "pulse",  n: "心拍数", unit: "bpm",  min: 30,  max: 220, decimals: 0 },',
    to: "" },
  { name: "心拍数の範囲チェックを緩める", guards: "30〜220bpmだけ受け入れる",
    file: "core.js", from: '    { k: "pulse",  n: "心拍数", unit: "bpm",  min: 30,  max: 220, decimals: 0 },',
    to: '    { k: "pulse",  n: "心拍数", unit: "bpm",  min: 0,  max: 999, decimals: 0 },' },
  { name: "保存で心拍数を読まない", guards: "入力した心拍数が保存される",
    file: "index.html", from: 'bpLow:g("h-bplow"), pulse:g("h-pulse")', to: 'bpLow:g("h-bplow")' },
  /* ---- ◯か月の推移（棒グラフ）の目もり ---- */
  { name: "棒グラフの目もりを勝手な式にする", guards: "目もりは core の計算",
    file: "index.html", from: "  const sc=Core.chartScale(vals, Core.CHART_TICKS);",
    to: "  const sc={lo:0,hi:Math.max.apply(null,vals)||1,step:1,ticks:[]};" },
  { name: "棒を下端から立てない", guards: "棒の高さが金額どおり",
    file: "index.html", from: '    ? `<rect x="${(cx-bw/2).toFixed(1)}" y="${y(v).toFixed(1)}" width="${bw.toFixed(1)}" height="${Math.max(2,(baseY-y(v))).toFixed(1)}" rx="2.5" fill="${color}"></rect>` : "";',
    to: '    ? `<rect x="${(cx-bw/2).toFixed(1)}" y="${y(v).toFixed(1)}" width="${bw.toFixed(1)}" height="${Math.max(2,(baseY-y(v))*0.8).toFixed(1)}" rx="2.5" fill="${color}"></rect>` : "";' },
  /* ---- カレンダーの日またぎ ---- */
  { name: "カレンダー描画で日またぎを見ない", guards: "翌日は今月に切り替わる",
    file: "index.html", from: "function renderCalendar(){\n  calSyncToToday();", to: "function renderCalendar(){" },
  { name: "日またぎ判定を常に「またいでいない」にする", guards: "翌日は今月に切り替わる",
    file: "index.html", from: "  if(now===calSeenDay) return false;   // 同じ日のうちは、手で選んだ月をそのまま保つ",
    to: "  if(true) return false;" },
  { name: "日またぎで月を今月に戻さない", guards: "翌日は今月に切り替わる",
    file: "index.html", from: "  calSeenDay=now;\n  calYM=calCurYM();\n  calSelected=null;\n  return true;",
    to: "  calSeenDay=now;\n  return true;" },
  /* ---- 国の切り替え（JP／US）：日本版を壊さないための砦 ---- */
  { name: "旧データを国なしのまま通す（JPへ寄せない）", guards: "国の印が無い記録はJP",
    file: "core.js", from: '    return normalizeCountry(t2 && t2.country ? t2.country : "JP");',
    to: "    return t2 && t2.country ? t2.country : null;" },
  { name: "記録を国で分けない（JPとUSが混ざる）", guards: "いまの国の記録だけを集計する",
    file: "core.js", from: "    const c = countryOf(settingsOrCountry);\n    return (Array.isArray(txs) ? txs : []).filter(function (t2) { return txCountry(t2) === c; });",
    to: "    return Array.isArray(txs) ? txs : [];" },
  { name: "当月の計算で国を見ない", guards: "computeMonth はいまの国だけを数える",
    file: "core.js", from: "    const all = txsForCountry(txs, s);",
    to: "    const all = Array.isArray(txs) ? txs : [];" },
  { name: "円にも小数を付ける", guards: "日本の金額表示は今までどおり ¥1,234",
    file: "core.js", from: '  const CURRENCY_DECIMALS = Object.freeze({ JPY: 0, USD: 2, GBP: 2, CAD: 2, AUD: 2 });',
    to: '  const CURRENCY_DECIMALS = Object.freeze({ JPY: 2, USD: 2, GBP: 2, CAD: 2, AUD: 2 });' },
  { name: "ドルを小数なしで出す", guards: "USは $1,234.56 の米国式",
    file: "core.js", from: "    const dec = currencyDecimals(rule.currency);",
    to: "    const dec = 0;" },
  { name: "国と通貨の組をほどく", guards: "国を正として基準通貨を必ず組にする",
    file: "core.js", from: "      currency: countryRule(country).currency,",
    to: "      currency: s.currency || countryRule(country).currency," },
  { name: "英語のときも日本語のカテゴリ名を出す", guards: "カテゴリは内部IDのまま表示だけ切り替える",
    file: "core.js", from: '    if (countryLang(settingsOrCountry) !== "en") return cat.n;',
    to: "    return cat.n;" },
  { name: "カテゴリを英語の文字列で保存する", guards: "保存するのは内部IDだけ",
    file: "core.js", from: "    const out = { id: id, type: type, amount: amount, cat: cat, date: tx.date, memo: memo, photo: photo };",
    to: '    const out = { id: id, type: type, amount: amount, cat: catName(type, cat, tx.country), date: tx.date, memo: memo, photo: photo };' },
  { name: "JPの記録にも国の印を付ける（保存の形が変わる）", guards: "JPは印を持たない",
    file: "core.js", from: '    if (tx.country && country !== "JP") out.country = country;',
    to: "    out.country = country;" },
  { name: "連携の国コードを決め打ちにする", guards: "連携の country_code は設定どおり",
    file: "core.js", from: "      country_code: c.settings.country,",
    to: '      country_code: "JP",' },
  { name: "連携の基準通貨を決め打ちにする", guards: "連携の base_currency は設定どおり",
    file: "core.js", from: "      base_currency: c.currency,\n      locale: countryLocale(c.settings),",
    to: '      base_currency: "JPY",\n      locale: countryLocale(c.settings),' },
  { name: "ライフプランへ渡す入力から国を落とす", guards: "渡す入力にも国と通貨を添える",
    file: "core.js", from: "      countryCode: normalizeSettings(s).country,\n      baseCurrency: normalizeSettings(s).currency,",
    to: "" },
  { name: "せっていで国を読まない（切り替えても保存されない）", guards: "国の選択が保存される",
    file: "index.html", from: "  \"f-country\": (s,v)=>{ s.country = Core.pickCountry(v); },",
    to: "  \"f-country\": (s,v)=>{ }," },
  { name: "まとめの記録一覧を国で絞らない", guards: "ほかの国の記録を並べない",
    file: "index.html", from: "  const list=[...Core.txsForCountry(state.tx, state.settings)].sort((a,b)=>",
    to: "  const list=[...state.tx].sort((a,b)=>" },
  { name: "新しい記録に国の印を付けない", guards: "USで記録したものはUSのものとして残す",
    file: "index.html", from: "  if(recCountry!==\"JP\") rec.country=recCountry;   // JPは印を持たない",
    to: "" },
  { name: "国を選び直しても保存も描き直しもしない", guards: "国を変えたらその場で切り替わる",
    file: "index.html", from: "  if(!switchMoneyCountry(el.value)){ toast(T(\"set.saveFailed\")); render(); return true; }\n  render(); return true;",
    to: "  return true;" },
  { name: "国の選択を change で受け取らない", guards: "選ぶ操作を受け取るつなぎがある",
    file: "index.html", from: "  if(onCountryPicked(el)) return;",
    to: "" },
  { name: "下のタブを日本語のまま置き去りにする", guards: "下のタブも国のことばで出る",
    file: "index.html", from: "function render(){\n  applyLang();", to: "function render(){" },

  /* ---- JP/US のお金プロファイル分離 ---- */
  { name: "旧JPのお金設定をJPへ退避しない", guards: "旧データの金額はJPに残りUSへ持ち込まない",
    file: "core.js", from: '    if (!out.JP && legacySettings && typeof legacySettings === "object") {',
    to: '    if (false) {' },
  { name: "初回USへJPの金額をコピーする", guards: "初回USは0/未設定から始まる",
    file: "core.js", from: '    const p = profiles && profiles[c] ? profiles[c] : {};',
    to: '    const p = profiles && profiles[c] ? profiles[c] : (profiles && profiles.JP ? profiles.JP : {});' },
  { name: "国切替で現在の金額を次の国へ持ち込む", guards: "JPの円金額を同じ数字のドルにしない",
    file: "index.html", from: '  state.settings=Core.settingsForCountry(state.moneyProfiles,next);',
    to: '  state.settings=Core.normalizeSettings(Object.assign({},state.settings,{country:next}));' },
  { name: "USのお金設定をプロファイルへ保存しない", guards: "US→JP→USでUS設定が戻る",
    file: "index.html", from: '  state.moneyProfiles[c]=Core.normalizeSettings(Object.assign({},state.settings,{country:c}));',
    to: '' },
  { name: "バックアップから国別お金プロファイルを外す", guards: "バックアップ復元後もJP/US両方を保持する",
    file: "core.js", from: '      moneyProfiles: normalizeMoneyProfiles(st.moneyProfiles, st.settings),\n',
    to: '' },

  /* ---- GB（英国）の国・通貨・日付 ---- */
  { name: "GBを選択対象から外す", guards: "GBを設定画面から選べる",
    file: "core.js", from: "  const SUPPORTED_COUNTRIES = Object.freeze([\"JP\", \"US\", \"GB\", \"CA\", \"AU\"]);",
    to: "  const SUPPORTED_COUNTRIES = Object.freeze([\"JP\", \"US\", \"CA\", \"AU\"]);" },
  { name: "GBの通貨をUSDにする", guards: "GBはGBP/£",
    file: "core.js", from: '    GB: Object.freeze({ country: "GB", currency: "GBP", locale: "en-GB", symbol: "£" }),',
    to: '    GB: Object.freeze({ country: "GB", currency: "USD", locale: "en-GB", symbol: "$" }),' },
  { name: "GBの日付を月日順にする", guards: "GBは日/月/年",
    file: "core.js", from: "    if (country === \"GB\" || country === \"AU\") return d + \"/\" + m + \"/\" + y;",
    to: "    if (country === \"AU\") return d + \"/\" + m + \"/\" + y;" },
  { name: "GBの見出し日付を米国順にする", guards: "GBは10 August",
    file: "core.js", from: "    if ([\"GB\",\"AU\"].includes(countryOf(settingsOrCountry))) return d + \" \" + MONTH_EN[m - 1];",
    to: "    if ([\"AU\"].includes(countryOf(settingsOrCountry))) return d + \" \" + MONTH_EN[m - 1];" },
  { name: "GBの月区切り表示を米国順にする", guards: "GBの区切りは20/7〜19/8",
    file: "core.js", from: "      if (country === \"GB\" || country === \"AU\") return d + \"/\" + m;\n      if (country === \"CA\") return pad2(m) + \"-\" + pad2(d);",
    to: "      if (country === \"AU\") return d + \"/\" + m;\n      if (country === \"CA\") return pad2(m) + \"-\" + pad2(d);" },
  { name: "CAを選択対象から外す", guards: "CAを設定画面から選べる",
    file: "core.js", from: "  const SUPPORTED_COUNTRIES = Object.freeze([\"JP\", \"US\", \"GB\", \"CA\", \"AU\"]);\n",
    to: "  const SUPPORTED_COUNTRIES = Object.freeze([\"JP\", \"US\", \"GB\", \"AU\"]);\n" },
  { name: "CAの通貨をUSDにする", guards: "CAはCAD/CA$",
    file: "core.js", from: '    CA: Object.freeze({ country: "CA", currency: "CAD", locale: "en-CA", symbol: "CA$" }),',
    to: '    CA: Object.freeze({ country: "CA", currency: "USD", locale: "en-CA", symbol: "$" }),' },
  { name: "CAの完全日付を米国順にする", guards: "CAはYYYY-MM-DD",
    file: "core.js", from: '    if (country === "CA") return String(y).padStart(4,"0") + "-" + pad2(m) + "-" + pad2(d);',
    to: '    if (country === "CA") return m + "/" + d + "/" + y;' },
  { name: "CAの月日を米国スラッシュ順にする", guards: "CAの短い日付はMM-DD",
    file: "core.js", from: '    if (country === "GB" || country === "AU") return d + "/" + m;\n    if (country === "CA") return pad2(m) + "-" + pad2(d);',
    to: '    if (country === "GB" || country === "AU") return d + "/" + m;\n    if (country === "CA") return m + "/" + d;' },
  { name: "CAの月区切り表示を米国順にする", guards: "CAの区切りは07-20〜08-19",
    file: "core.js", from: '      if (country === "CA") return pad2(m) + "-" + pad2(d);',
    to: '      if (country === "CA") return m + "/" + d;' },

  /* ---- AU（オーストラリア）の国・通貨・日付 ---- */
  { name: "AUを選択対象から外す", guards: "AUを設定画面から選べる",
    file: "core.js", from: '  const SUPPORTED_COUNTRIES = Object.freeze(["JP", "US", "GB", "CA", "AU"]);',
    to: '  const SUPPORTED_COUNTRIES = Object.freeze(["JP", "US", "GB", "CA"]);' },
  { name: "AUの通貨をUSDにする", guards: "AUはAUD/A$",
    file: "core.js", from: '    AU: Object.freeze({ country: "AU", currency: "AUD", locale: "en-AU", symbol: "A$" }),',
    to: '    AU: Object.freeze({ country: "AU", currency: "USD", locale: "en-AU", symbol: "$" }),' },
  { name: "AUの完全日付を米国順にする", guards: "AUは日/月/年",
    file: "core.js", from: '    if (country === "GB" || country === "AU") return d + "/" + m + "/" + y;',
    to: '    if (country === "GB" || country === "AU") return m + "/" + d + "/" + y;' },
  { name: "AUの見出し日付を米国順にする", guards: "AUは10 August",
    file: "core.js", from: '    if (["GB","AU"].includes(countryOf(settingsOrCountry))) return d + " " + MONTH_EN[m - 1];',
    to: '    if (["GB","AU"].includes(countryOf(settingsOrCountry))) return MONTH_EN[m - 1] + " " + d;' },
  { name: "AUの月区切り表示を米国順にする", guards: "AUの区切りは20/7〜19/8",
    file: "core.js", from: '      if (country === "GB" || country === "AU") return d + "/" + m;',
    to: '      if (country === "GB" || country === "AU") return m + "/" + d;' },

  /* ---- カレンダーは暦の月（家計の区切りキーではない） ---- */
  { name: "カレンダーの今月を区切りキーにする", guards: "起点20日でも暦の月を表示",
    file: "index.html", from: "function calCurYM(){ return ymOf(todayISO()); }",
    to: "function calCurYM(){ return curYM(); }" },

  /* ---- 2026-08 の検査で直したところ ---- */

  /* ① 写真の data URL は末尾まで確かめる（属性を抜け出させない） */
  { name: "写真の検証を先頭だけにする", guards: "写真は末尾まで検証",
    file: "core.js", from: '  const PHOTO_DATA_URL = /^data:image\\/(png|jpeg|jpg|gif|webp);base64,[A-Za-z0-9+/]+={0,2}$/;',
    to: '  const PHOTO_DATA_URL = /^data:image\\/[a-z+.-]+;base64,/i;' },
  { name: "日記の写真をエスケープせず出す", guards: "写真は属性に入れる前に逃がす",
    file: "index.html", from: '`<img src="${escapeAttr(d.photo)}" style="width:40px',
    to: '`<img src="${d.photo}" style="width:40px' },
  { name: "escapeHtml が引用符を逃がさない", guards: "属性の引用符を逃がす",
    file: "index.html", from: `function escapeHtml(s){ return String(s||"").replace(/[&<>"']/g,`,
    to: `function escapeHtml(s){ return String(s||"").replace(/[&<>]/g,` },

  /* ④ 金額の上限と、整える場所をひとつにすること */
  { name: "金額の上限を効かせない", guards: "金額は上限で止める",
    file: "index.html", from: "  const amount=Math.min(typed, cap);",
    to: "  const amount=typed;" },
  { name: "記録を整えずに保存する", guards: "記録は必ず計算コアを通す",
    file: "index.html", from: "  const safe=Core.normalizeTransaction(rec);",
    to: "  const safe=Object.assign({},rec);" },
  { name: "読み込んだ記録を整えない", guards: "読み込みでも記録を整える",
    file: "index.html", from: "tx:Core.normalizeTxList(s.tx)",
    to: "tx:(Array.isArray(s.tx)?s.tx:[])" },
  { name: "編集で記録の国を取り違える", guards: "直しても記録の国は変わらない",
    file: "index.html", from: "  const recCountry = editIdx>=0 ? txCountryOf(state.tx[editIdx]) : Core.normalizeCountry(st.country||curCountry());",
    to: "  const recCountry = curCountry();" },
  { name: "グラフの左端を月ずらしで出す", guards: "月末でも1か月ぶん出る",
    file: "index.html", from: "  return Core.shiftDate(todayISO(), -back);",
    to: "  const d=new Date(); d.setMonth(d.getMonth()-1); return d.toISOString().slice(0,10);" },
  { name: "グラフの左端をUTCで書き出す", guards: "左端はローカルの日付",
    file: "index.html", from: "const HEALTH_RANGE_DAYS={ day:1, week:7, month:30 };",
    to: "const HEALTH_RANGE_DAYS={ day:0, week:6, month:29 };" },

  /* ⑦ カメラの起動レース */
  { name: "許可待ちの映像を捨てない", guards: "離れたら届いた映像を捨てる",
    file: "index.html", from: '  if(gen!==pGen || view!=="pulse"){',
    to: "  if(false){" },
  { name: "停止で世代を進めない", guards: "許可待ちの測定も止める",
    file: "index.html", from: "  pGen++;              // 許可を待っている最中の測定も、ここで無効にする",
    to: "  // pGen++;" },

  /* ⑧ 度で計算するときの 90 の倍数 */
  { name: "度の特別扱いをやめる", guards: "tan(90)は答えを出さない",
    file: "core.js", from: "      const special = sciDegSpecial(name, x);",
    to: "      const special = undefined;" },
  { name: "弧度でも度の丸めを使う", guards: "弧度では丸めない",
    file: "core.js", from: '    if (deg && (name === "sin" || name === "cos" || name === "tan") && Number.isFinite(x)) {',
    to: '    if ((name === "sin" || name === "cos" || name === "tan") && Number.isFinite(x)) {' },

  /* ⑥ service worker */
  { name: "失敗した返事もキャッシュに入れる", guards: "失敗は焼き付けない",
    file: "sw.js", from: '  return !!res && res.ok && res.status === 200 && res.type === "basic";',
    to: "  return !!res;" },

  /* ---- ⑤第1段階：最小通貨単位への移行 ---- */

  { name: "JPにも100を掛ける", guards: "JPは1=1円",
    file: "core.js", from: '  const MINOR_UNIT_SCALE = Object.freeze({ JPY: 1, USD: 100, GBP: 100, CAD: 100, AUD: 100 });',
    to: '  const MINOR_UNIT_SCALE = Object.freeze({ JPY: 100, USD: 100, GBP: 100, CAD: 100, AUD: 100 });' },
  { name: "GBだけ倍率を取り違える", guards: "GBも1=1ペニー",
    file: "core.js", from: '  const MINOR_UNIT_SCALE = Object.freeze({ JPY: 1, USD: 100, GBP: 100, CAD: 100, AUD: 100 });',
    to: '  const MINOR_UNIT_SCALE = Object.freeze({ JPY: 1, USD: 100, GBP: 1, CAD: 100, AUD: 100 });' },
  { name: "記録をいまの国で一括換算する", guards: "記録はtx.countryで換算",
    file: "core.js", from: "      const scale = minorScale(normalizeCountry(t.country));   // 印が無ければJP＝1",
    to: "      const scale = minorScale(normalizeCountry((st.settings || {}).country));" },
  { name: "プロファイルをいまの国で一括換算する", guards: "設定は各プロファイルの国で換算",
    file: "core.js", from: "        const country = normalizeCountry(c);",
    to: "        const country = normalizeCountry((st.settings || {}).country);" },
  { name: "移行済みでも、もう一度換算する", guards: "二重移行しない",
    file: "core.js", from: "    return Number(st.dataVersion) !== DATA_VERSION;",
    to: "    return true;" },
  { name: "移行しても印を付けない", guards: "移行したら印を付ける",
    file: "core.js", from: "    out.dataVersion = DATA_VERSION;",
    to: "    out.dataVersion = st.dataVersion;" },
  { name: "％や年齢にも100を掛ける", guards: "お金の欄だけ換算",
    file: "core.js", from: '      banks: Object.freeze(["balance", "monthlyDeposit"]),          // interestPct は％',
    to: '      banks: Object.freeze(["balance", "monthlyDeposit", "interestPct"]),' },
  { name: "お金の欄をひとつ換算し忘れる", guards: "お金の欄は全部換算",
    file: "core.js", from: '      lumpSums: Object.freeze(["amount"]),',
    to: '      lumpSums: Object.freeze([]),' },
  { name: "古いバックアップを最小単位として読む", guards: "旧バックアップは主単位",
    file: "core.js", from: "    if (ver <= BACKUP_VERSION_MAJOR_UNITS) {",
    to: "    if (false) {" },
  { name: "新しすぎるバックアップも読み込む", guards: "新しすぎたら断る",
    file: "core.js", from: "    if (ver > BACKUP_VERSION) {",
    to: "    if (false) {" },
  { name: "ライフプランへ最小単位のまま渡す", guards: "渡すのは主単位",
    file: "core.js", from: "      const out = scale === 1 ? n : n / scale;",
    to: "      const out = n;" },
  { name: "渡す前の検算をやめる", guards: "食い違ったら渡さない",
    file: "core.js", from: "      if (Math.round(out * scale) !== Math.round(n)) {",
    to: "      if (false) {" },
  { name: "ライフプラン入力を最小単位のまま渡す", guards: "入力も主単位で渡す",
    file: "core.js", from: "    const major = settingsToMajor(s);",
    to: "    const major = JSON.parse(JSON.stringify(s || {}));" },
  { name: "控えが取れなくても移行する", guards: "控えが取れたときだけ移行",
    file: "index.html", from: "      if(backupBeforeMigration(raw)){",
    to: "      if(true){" },
  { name: "控えを書けたか確かめない", guards: "控えは読み戻して確かめる",
    file: "index.html", from: "      return localStorage.getItem(MIGRATION_BACKUP_KEY) === text;",
    to: "      return true;" },
  { name: "移行を見送っても保存してしまう", guards: "見送り中は保存しない",
    file: "index.html", from: "  if(migrationBlocked){ lastSaveError = new Error(\"QuotaExceededError\"); lastSaveError.name=\"QuotaExceededError\"; return false; }",
    to: "  if(false){ return false; }" },
  { name: "見送ったのに印を付ける", guards: "見送ったら印を付けない",
    file: "index.html", from: "    if(!migrationBlocked) out.dataVersion=Core.DATA_VERSION;",
    to: "    out.dataVersion=Core.DATA_VERSION;" },
  { name: "画面へ主単位に戻さず出す", guards: "表示は主単位へ戻す",
    file: "index.html", from: "function yen(v){ return Core.formatAmount(v, state.settings); }",
    to: "function yen(v){ return Core.formatMoney(v, state.settings); }" },
  { name: "打ち込みを最小単位へ直さない", guards: "打ち込みは最小単位へ直す",
    file: "index.html", from: "  const typed=Core.majorTextToMinorRound(st.amount, decOf(recCountry));",
    to: "  const typed=Math.round(Number(String(st.amount).replace(/[^0-9.]/g,\"\"))||0);" },
  { name: "直すときいまの国で換算する", guards: "直すときも記録の国で換算",
    file: "index.html", from: "  const recCountry = editIdx>=0 ? txCountryOf(state.tx[editIdx]) : Core.normalizeCountry(st.country||curCountry());",
    to: "  const recCountry = curCountry();" },

  /* ---- ⑤第2段階：小数の打ち込み・電卓・レシート読み取り ---- */

  /* 旧「円にも小数点キーを出す」は、国で並びを分ける作りをやめたため差し替えた。
     いまは5か国とも 0 / . / 00 で固定。国ごとの分岐そのものが無い。 */
  { name: "電卓の並びを国で分ける", guards: "キーの並びは5か国とも同じ",
    file: "index.html", from: '    ${k("0","0")}${k(".",".","zero")}${k("00","00","zero")}',
    to: '    ${sheetDec() ? `${k("0","0")}${k(".",".","zero")}${k("00","00","zero")}` : `${k("0","0")}${k("00","00","zero")}${k("000","000","zero")}`}' },
  { name: "小数点キーを出さない", guards: "5か国とも小数点キーがある",
    file: "index.html", from: '${k("0","0")}${k(".",".","zero")}${k("00","00","zero")}',
    to: '${k("0","0")}${k("00","00","zero")}${k("000","000","zero")}' },
  { name: "円でも小数点を受け付ける", guards: "5か国とも小数点キーが効く",
    file: "core.js", from: "    if (k === \".\" || k === \"．\") {\n      if (c.done)",
    to: "    if (k === \".\" || k === \"．\") {\n      if (!c.dec) return c;\n      if (c.done)" },
  { name: "小数点を2つ置けるようにする", guards: "小数点は1つだけ",
    file: "core.js", from: '      if (c.cur.indexOf(".") >= 0) return c;           // 2つ目の小数点は置かない',
    to: "      if (false) return c;" },
  { name: "小数の桁数を制限しない", guards: "小数は通貨の桁数まで",
    file: "core.js", from: '    return intPart + "." + frac.slice(0, d);',
    to: '    return intPart + "." + frac;' },
  { name: "掛け算で倍率をならさない", guards: "$1.00×3は$3.00",
    file: "core.js", from: '    if (op === "*") return Math.round((a * b) / s);',
    to: '    if (op === "*") return a * b;' },
  { name: "割り算で倍率をならさない", guards: "$10.00÷4は$2.50",
    file: "core.js", from: '    if (op === "/") return b === 0 ? null : Math.round((a / b) * s);',
    to: '    if (op === "/") return b === 0 ? null : Math.round(a / b);' },
  { name: "打ち込みを小数のまま数にする", guards: "字のまま桁を組む",
    file: "core.js", from: "    return Number(intPart) * Math.pow(10, d) + frac;",
    to: "    return Math.round(Number(t) * Math.pow(10, d));" },
  { name: "打ち込み欄でセントを切り捨てる", guards: "直してもセントが落ちない",
    file: "index.html", from: "function sheetMajor(minorValue, country){ return Core.minorToMajorText(minorValue, decOf(country)); }",
    to: "function sheetMajor(minorValue, country){ return String(Math.round(Core.toMajor(minorValue, country||state.settings))); }" },
  { name: "記録の電卓をいまの国の桁数で作る", guards: "電卓は記録の国の桁数",
    file: "index.html", from: "    if(t) return decOf(txCountryOf(t));", to: "    if(t) return decOf(curCountry());" },
  { name: "レシートの小数を読まない", guards: "$9.99を99と読まない",
    file: "core.js", from: "    const re = d > 0\n      ? /(?:[¥￥$£€]\\s*)?(\\d{1,3}(?:,\\d{3})+(?:\\.\\d{1,2})?|\\d{1,7}(?:\\.\\d{1,2})?)(?![\\d%％])/g",
    to: "    const re = d > 0\n      ? /(?:[¥￥$£€]\\s*)?(\\d{1,3}(?:,\\d{3})+|\\d{2,7})(?![\\d%％])/g" },
  { name: "小計を合計として拾う", guards: "Subtotalを合計にしない",
    file: "core.js", from: "|sub\\s*-?\\s*total|change\\s*due|change", to: "|change\\s*due|change" },
  { name: "お釣りを合計として拾う", guards: "Changeを合計にしない",
    file: "core.js", from: "|change\\s*due|change|cash\\s*tend", to: "|cash\\s*tend" },
  { name: "英語の言い回しを合計と見なさない", guards: "Amount Dueも合計",
    file: "core.js", from: "|total\\s*amount|amount\\s*payable|total\\s*payable|total\\s*to\\s*pay|total\\s*pay\\b|you\\s*pay|net\\s*payable|purchase\\s*total|total)/i;",
    to: "|total)/i;" },
  { name: "レシートの桁数を渡さない", guards: "読み取りに通貨の桁数を渡す",
    file: "index.html", from: "        Core.amountDetails(data.text, sheetDec()).forEach(d=>{",
    to: "        Core.amountDetails(data.text).forEach(d=>{" },
  { name: "候補を主単位へ戻さずに入れる", guards: "候補は最小単位で持つ",
    file: "index.html", from: "    sheetState.amount=Core.minorToMajorText(pick.dataset.pick, sheetDec());",
    to: "    sheetState.amount=String(pick.dataset.pick);" },
  { name: "設定の小数を切り捨てる", guards: "設定にも小数を入れられる",
    file: "index.html", from: "function settingMinor(v, settings){ return Core.majorTextToMinorRound(v, decOf(settings)); }",
    to: "function settingMinor(v, settings){ return Core.toMinor(settingNum(v), settings); }" },
  { name: "金額の欄に小数のキーボードを出さない", guards: "5か国とも同じキーボード",
    file: "index.html", from: "function moneyInputMode(){ return \"decimal\"; }",
    to: "function moneyInputMode(){ return decOf()>0 ? \"decimal\" : \"numeric\"; }" },
  { name: "英語圏の目もりに M を出さない", guards: "1,500,000は1.5M",
    file: "index.html", from: '    if(v>=1000000){ return tickShort(v/1000000)+"M"; }', to: "" },
  { name: "英語圏の目もりに k を出さない", guards: "1,500は1.5k",
    file: "index.html", from: '    if(v>=1000){ return tickShort(v/1000)+"k"; }', to: "" },
  { name: "円でも k を出す", guards: "日本は万のまま",
    file: "index.html", from: '  if(isEn()){\n    if(v>=1000000){', to: "  if(true){\n    if(v>=1000000){" },
  { name: "目もりを最小単位のまま出す", guards: "目もりは主単位",
    file: "index.html", from: "  const v = toMajor(minorValue);", to: "  const v = minorValue;" },
  { name: "目もりの短縮で小数を捨てる", guards: "1.5kを1kにしない",
    file: "index.html", from: "function tickShort(n){ return Number.isInteger(n) ? n : Math.round(n*10)/10; }",
    to: "function tickShort(n){ return Math.round(n); }" },
  { name: "税込みの合計より税の語を優先する", guards: "Total incl VATを捨てない",
    file: "core.js", from: "      if (!STRONG_TOTAL_KW.test(line) && SKIP_KW.test(line)) continue;",
    to: "      if (SKIP_KW.test(line)) continue;" },
  { name: "はっきりした合計の言い方を知らない", guards: "Total incl VATを捨てない",
    file: "core.js", from: "|total\\s*payable|total\\s*to\\s*pay|total\\s*pay\\b|total\\s*inc)/i;",
    to: ")/i;" },
  { name: "英語の税を拾ってしまう", guards: "VAT/GST/HST/PST/QSTは合計でない",
    file: "core.js", from: "|\\bvat\\b|\\bgst\\b|\\bhst\\b|\\bpst\\b|\\bqst\\b", to: "" },
  { name: "カード会社名を拾ってしまう", guards: "支払い手段は合計でない",
    file: "core.js", from: "|visa|mastercard|amex|eftpos|interac", to: "" },
  { name: "チップ・値引きを拾ってしまう", guards: "チップ・値引きは合計でない",
    file: "core.js", from: "|you\\s*saved|loyalty|reward|tip|gratuity|service\\s*charge", to: "" },
  { name: "数量・単価を拾ってしまう", guards: "数量・単価は合計でない",
    file: "core.js", from: "|unit\\s*price|\\bqty\\b|quantity", to: "" },

  /* ---- 関数電卓の答えを家計簿へ入れる導線 ---- */
  { name: "関数電卓の記録ボタンを出さない", guards: "＝のあと記録するボタンが出る",
    file: "index.html", from: '      ? `<button class="btn-main sciuse" data-act="sci-record">',
    to: '      ? `<button class="btn-main sciuse" data-act="sci-none">' },
  { name: "記録ボタンの金額を主単位のまま出す", guards: "ボタンと記録画面の金額が一致",
    file: "index.html", from: "  const amount=Core.sciRecordAmount(s, decOf());",
    to: "  const amount=Core.sciAmount(s);" },
  { name: "記録画面へ最小単位のまま渡す", guards: "記録画面には主単位の字で入る",
    file: "index.html", from: "    sheetState.amount=Core.minorToMajorText(minor, sheetDec());",
    to: "    sheetState.amount=String(minor);" },
  /* 旧「その通貨で表せない答えも記録させる」は差し替えた。
     以前は割り切れない答えを門前払いしていたが、そのせいで日本では
     1000÷3 や √2 の答えを記録できなかった。いまは丸めて記録する。
     代わりに「丸め方が切り捨てになっていないか」を見張る
     （切り捨てだと ¥1.5 が黙って ¥1 になる）。 */
  { name: "その通貨で表せない答えも記録させる", guards: "割り切れない答えは丸めて記録する",
    file: "core.js", from: "    const minor = Math.round(v * scale);",
    to: "    const minor = Math.floor(v * scale);" },
  { name: "0や負の答えも記録させる", guards: "1以上の金額だけ記録する",
    file: "core.js", from: "    if (!(minor > 0)) return null;", to: "" },

  /* ---- 円でも小数点が打てる（A案：丸めたことを必ず知らせる） ---- */

  { name: "丸めたことを知らせない", guards: "黙って額を変えない",
    file: "index.html", from: "    if(rounded){", to: "    if(false){" },
  { name: "丸めたかどうかを見ない", guards: "黙って額を変えない",
    file: "index.html", from: "  const rounded=Core.majorTextHasExtraDecimals(st.amount, decOf(recCountry));",
    to: "  const rounded=false;" },
  { name: "細かい桁の判定を通貨の桁で切らない", guards: "その通貨の桁で見分ける",
    file: "core.js", from: "    return /[1-9]/.test(frac.slice(d));", to: "    return /[1-9]/.test(frac);" },
  { name: "打ち込みを切り捨てにする", guards: "1円へ四捨五入する",
    file: "core.js", from: '    if (Number(frac.charAt(d) || "0") >= 5) v += 1;   // 次の桁で繰り上げる', to: "" },
  { name: "打てる小数の桁を通貨まかせにする", guards: "5か国とも同じだけ打てる",
    file: "core.js", from: "  function calcInputDec(c) { return Math.max((c && c.dec) || 0, CALC_INPUT_DEC); }",
    to: "  function calcInputDec(c) { return (c && c.dec) || 0; }" },
  /* ---- バックアップ：moneyProfiles導入途中の海外設定 ---- */
  { name: "USバックアップの設定プロファイルを補完しない", guards: "moneyProfiles無しでもUS設定を失わない",
    file: "core.js",
    from: "    if (!backupProfiles[backupSettings.country]) {\n      backupProfiles[backupSettings.country] = profileSettings(src.settings, backupSettings.country);\n    }",
    to: "" },
  { name: "欠けた海外プロファイルをJPとして補完する", guards: "復元対象国の設定をその国へ補完する",
    file: "core.js",
    from: "      backupProfiles[backupSettings.country] = profileSettings(src.settings, backupSettings.country);",
    to: '      backupProfiles.JP = profileSettings(src.settings, "JP");' },

  /* ---- ライフプラン連携：行IDの一意性 ---- */
  { name: "ライフプラン連携の重複IDをそのまま残す", guards: "同じ種類の行IDは一意",
    file: "core.js",
    from: "        if (id && !seen[id]) { seen[id] = true; return r; }",
    to: "        if (id) { seen[id] = true; return r; }" },
  { name: "新しい連携IDの衝突を確認しない", guards: "生成IDも既存IDと重複しない",
    file: "core.js",
    from: "        do { id = lpId(gen()); } while (!id || seen[id]);",
    to: "        id = lpId(gen());" },

  /* ---- 海外ライフプラン連携：銀行積立 ---- */
  { name: "海外銀行積立でmonthlyDepositを見ない", guards: "GB/CA/AUのcash savingsへ正しい年額を渡す",
    file: "core.js",
    from: '      const monthlyBank = a.banks.reduce(function (sum, b) { return sum + (Number(b.monthlyDeposit) || 0); }, 0);',
    to: '      const monthlyBank = 0;' },
  { name: "海外銀行積立を1件目だけで計算する", guards: "複数銀行の月額を合算する",
    file: "core.js",
    from: '      const monthlyBank = a.banks.reduce(function (sum, b) { return sum + (Number(b.monthlyDeposit) || 0); }, 0);',
    to: '      const monthlyBank = a.banks.length ? (Number(a.banks[0].monthlyDeposit) || 0) : 0;' },

  /* ---- バックアップ復元確認の多言語化 ---- */
  { name: "海外でもバックアップ復元確認を日本語固定にする", guards: "US復元確認は英語のみ",
    file: "index.html",
    from: '    const ok = confirm(L(',
    to: '    const ok = confirm((' },

  /* ---- OCR進行表示の多言語化 ---- */
  { name: "OCR画像調整中を日本語固定に戻す", guards: "海外OCR進行表示に日本語を残さない",
    file: "index.html",
    from: '  setStatus(L("画像を調整しています…","Adjusting the image…"));',
    to: '  setStatus("画像を調整しています…");' },

  /* ---- 毎月固定の繰越確認の多言語化 ---- */
  { name: "海外でも毎月固定の繰越確認を日本語固定にする", guards: "繰越確認は海外で英語",
    file: "index.html",
    from: '  const ok=confirm(L(\n    `先月（${plan.from.replace("-","年")}月）の毎月固定を、今月へ入れます。',
    to: '  const ok=confirm((\n    `先月（${plan.from.replace("-","年")}月）の毎月固定を、今月へ入れます。' },

  /* ---- レシート画面の案内文の多言語化 ---- */
  { name: "レシート枠合わせ案内を日本語固定に戻す", guards: "海外レシート案内は英語",
    file: "index.html",
    from: 'sheetState.ocrNote=L("枠を合計に合わせて、読み取りボタンを押してください","Move the box over the total, then tap Read");',
    to: 'sheetState.ocrNote="枠を合計に合わせて、読み取りボタンを押してください";' },

  /* ---- 毎月固定：同カテゴリ複数件の繰越 ---- */
  { name: "毎月固定の入力済み判定をカテゴリ1個の真偽値に戻す", guards: "同カテゴリ複数件も1件ずつ繰越",
    file: "core.js",
    from: "        done[t.cat] = (done[t.cat] || 0) + 1;",
    to: "        done[t.cat] = 1;" },
  { name: "毎月固定の入力済み件数を消費しない", guards: "同カテゴリの残り件数を繰越",
    file: "core.js",
    from: "      if (already) done[t.cat] -= 1;",
    to: "" },

  /* ---- 写真容量管理：日記写真も含める ---- */
  { name: "容量表示から日記写真を外す", guards: "写真容量に日記写真も含む",
    file: "core.js",
    from: "      SUPPORTED_COUNTRIES.forEach(function (c) {\n        const d = profiles[c] && profiles[c].diary;",
    to: "" },
  { name: "写真一括削除で日記写真を残す", guards: "写真をすべて消すは日記写真も対象",
    file: "index.html",
    from: "    Object.keys(d).forEach(date=>{ if(d[date]&&d[date].photo){ delete d[date].photo; n++; } });",
    to: "" },

  /* ---- 日記写真：保存前の下書きをstateへ確定しない ---- */
  { name: "日記写真を選んだだけで本文をstateへ保存する", guards: "日記本文は保存ボタンでのみ確定",
    file: "index.html",
    from: '    render(); const t2=$("d-text"); if(t2) t2.value=keepText;',
    to: '    const cur=state.diary[diaryEditDate||todayISO()]||{}; cur.text=keepText; render(); const t2=$("d-text"); if(t2) t2.value=keepText;' },

  /* ---- 移行バックアップ：国別日記写真も容量削減 ---- */
  { name: "移行控えで国別日記写真を残す", guards: "容量不足時は全プロフィールの日記写真も外す",
    file: "index.html",
    from: '    if(lite.personalProfiles && typeof lite.personalProfiles === "object"){',
    to: '    if(false && lite.personalProfiles && typeof lite.personalProfiles === "object"){' },

  /* ---- バックアップ：現在国の個人記録を先に同期 ---- */
  { name: "バックアップ前の個人記録同期を外す", guards: "最新の現在国個人記録を国別バックアップへ入れる",
    file: "index.html",
    from: "function exportBackup(){\n  /* バックアップは、その瞬間に画面で使っている現在国の設定・個人記録を",
    to: "function exportBackup(){\n  syncPersonalProfile = function(){};\n  /* バックアップは、その瞬間に画面で使っている現在国の設定・個人記録を" },

  /* ---- 記録電卓履歴：国別分離 ---- */
  { name: "記録電卓履歴を国で絞らない", guards: "記録電卓履歴は国別",
    file: "index.html",
    from: "    .filter(h=>Core.normalizeCountry(h&&h.country)===historyCountry)",
    to: "" },
  { name: "編集時の電卓履歴を現在国で表示する", guards: "編集履歴は記録自身の国",
    file: "index.html",
    from: "    if(tx) historyCountry=txCountryOf(tx);",
    to: "" },


  { name: "編集した電卓履歴を現在国へ混ぜる", guards: "編集履歴の保存先も記録自身の国",
    file: "index.html",
    from: "  calcHistCandidate.country=recCountry;",
    to: "" },


  { name: "記録電卓履歴を全世界50件に戻す", guards: "記録電卓履歴の上限は国ごと",
    file: "index.html",
    from: "    const sameCountry=allRecordCalcHistory.filter(h=>Core.normalizeCountry(h&&h.country)===recCountry).slice(-50);",
    to: "    const sameCountry=allRecordCalcHistory.slice(-50);" },


  { name: "関数電卓履歴を全世界共有に戻す", guards: "関数電卓履歴も国別",
    file: "index.html",
    from: "      .filter(h=>Core.normalizeCountry(h&&h.country)===c)",
    to: "      .filter(h=>true)" },
  { name: "関数電卓履歴削除で全世界を消す", guards: "関数電卓履歴削除は現在国だけ",
    file: "index.html",
    from: "    state.calcHistory=(state.calcHistory||[]).filter(h=>Core.normalizeCountry(h&&h.country)!==c);",
    to: "    state.calcHistory=[];" },


  { name: "容量超過でも古い移行控えを解放しない", guards: "写真記録の容量不足を旧控え解放で救済",
    file: "index.html",
    from: '        if(typeof localStorage.removeItem==="function") localStorage.removeItem(MIGRATION_BACKUP_KEY);',
    to: '        /* obsolete migration backup kept */' },




  { name: "OCR金額を電卓状態へ同期しない", guards: "読み取った金額をそのまま記録できる",
    file: "index.html",
    from: "    st.amount=Core.minorToMajorText(ranked[0].amount, sheetDec());\n    /* 金額欄は st.calc が正本。amount だけ変えると renderSheet/saveTx で古い0円へ戻る。 */\n    st.calc=Core.calcFrom(st.amount, sheetCalcDec());",
    to: "    st.amount=Core.minorToMajorText(ranked[0].amount, sheetDec());" },


  { name: "レシート写真だけ外すボタンを隠す", guards: "写真だけ削除できる",
    file: "index.html",
    from: '       <button class="photobtn" data-act="rm-photo">${L("写真だけ外す","Remove photo")}</button>',
    to: '' },


  { name: "レシート撮影キャンセル時に記録画面へ戻さない", guards: "撮影キャンセルでも入力を保持する",
    file: "index.html",
    from: '    ensureSheetForPhoto();\n    clearPending();\n    setStatus(L("撮影をキャンセルしました。入力内容はそのままです","Photo capture cancelled. Your entries are unchanged"));\n    renderSheet(); showSheet(true);',
    to: '    clearPending();' },


  { name: "無効な記録でも電卓履歴だけ残す", guards: "記録検証失敗時の幽霊履歴を防ぐ",
    file: "index.html",
    from: '  if(calcHistCandidate){\n    calcHistCandidate.txId=rec.id;',
    to: '  if(false && calcHistCandidate){\n    calcHistCandidate.txId=rec.id;' },


  { name: "消えた記録の編集をそのまま続ける", guards: "古い編集画面から幽霊更新しない",
    file: "index.html",
    from: '  if(st.mode==="edit" && editIdx<0){',
    to: '  if(false && st.mode==="edit" && editIdx<0){' },


  { name: "保存不能でも写真容量不足として再試行する", guards: "写真フォールバック理由を容量不足に限定",
    file: "index.html",
    from: '  if(photo && isQuotaError(lastSaveError)){',
    to: '  if(photo){' },


  { name: "カメラ復帰で毎月固定ONを失う", guards: "撮影をまたいでも毎月固定を保持",
    file: "index.html",
    from: 'const light={mode:st.mode,id:st.id||null,country:Core.normalizeCountry(st.country||curCountry()),type:st.type,amount:st.amount,cat:st.cat,date:st.date,memo:st.memo,recurring:st.type==="expense" && st.recurring===true,calc:st.calc||null};',
    to: 'const light={mode:st.mode,id:st.id||null,country:Core.normalizeCountry(st.country||curCountry()),type:st.type,amount:st.amount,cat:st.cat,date:st.date,memo:st.memo,recurring:false,calc:st.calc||null};' },


  { name: "カメラ退避から電卓状態を外す", guards: "計算途中も撮影後に復元",
    file: "index.html",
    from: 'recurring:st.type==="expense" && st.recurring===true,calc:st.calc||null',
    to: 'recurring:st.type==="expense" && st.recurring===true,calc:null' },

  { name: "一時保存の書込み確認を存在確認だけに戻す", guards: "保存内容の一致まで確認",
    file: "index.html",
    from: 'return sessionStorage.getItem(PENDING_KEY)===encoded;',
    to: 'return sessionStorage.getItem(PENDING_KEY)!==null;' },


  { name: "撮影中に新規記録の国を現在国へすり替える", guards: "記録開始時の国を固定",
    file: "index.html",
    from: '  const recCountry = editIdx>=0 ? txCountryOf(state.tx[editIdx]) : Core.normalizeCountry(st.country||curCountry());',
    to: '  const recCountry = editIdx>=0 ? txCountryOf(state.tx[editIdx]) : curCountry();' },

  { name: "消えた編集元をカメラ復帰で復元する", guards: "stale editを復元しない",
    file: "index.html",
    from: '  if(p.mode==="edit" && !(state.tx||[]).some(t=>t&&t.id===p.id)){',
    to: '  if(false && p.mode==="edit" && !(state.tx||[]).some(t=>t&&t.id===p.id)){' },


  { name: "バックアップ前の国別設定同期を外す", guards: "最新設定をバックアップへ入れる",
    file: "index.html", from: "  syncMoneyProfile();\n  syncPersonalProfile();", to: "  syncPersonalProfile();" },

  { name: "バックアップ復元で古い電卓履歴を残す", guards: "履歴も同じバックアップへ置換",
    file: "index.html",
    from: "    state.calcHistory = backupCalcHistory(rawBackup && rawBackup.calcHistory);\n    state.recordCalcHistory = backupRecordCalcHistory(rawBackup && rawBackup.recordCalcHistory, restored.tx);",
    to: "    /* calculator histories left unchanged */" },


  { name: "バックアップ関数電卓履歴を無制限に復元する", guards: "各国20件上限",
    file: "index.html",
    from: "    out.push(...normalized.filter(h=>h.country===c).slice(0,20));",
    to: "    out.push(...normalized.filter(h=>h.country===c));" },

  { name: "存在しない記録への電卓履歴リンクを復元する", guards: "txIdリンク整合性",
    file: "index.html",
    from: "    if(!linked || Core.normalizeCountry(h.country)!==linked.country) return null;",
    to: "    if(false && (!linked || Core.normalizeCountry(h.country)!==linked.country)) return null;" },


  { name: "国別個人記録の配列をプロファイルとして許す", guards: "personalProfiles形検証",
    file: "index.html",
    from: "  if(v && typeof v===\"object\" && !Array.isArray(v)){",
    to: "  if(v && typeof v===\"object\"){" },

  { name: "各国個人記録の配列を許す", guards: "各国personal profile形検証",
    file: "index.html",
    from: "      if(Object.prototype.hasOwnProperty.call(v,c) && v[c] && typeof v[c]===\"object\" && !Array.isArray(v[c])) out[c]=normalizePersonalData(v[c]);",
    to: "      if(Object.prototype.hasOwnProperty.call(v,c) && v[c] && typeof v[c]===\"object\") out[c]=normalizePersonalData(v[c]);" },


  { name: "1か国分の個人記録で配列を許す", guards: "personalData形検証",
    file: "index.html",
    from: "  const src=(v && typeof v===\"object\" && !Array.isArray(v))?v:{};",
    to: "  const src=(v && typeof v===\"object\")?v:{};" },


  { name: "空の個人記録でpulse配列を国間共有する", guards: "空個人記録の独立性",
    file: "index.html",
    from: "  return { health:{}, diary:{}, plans:{}, pulse:[] };",
    to: "  return { health:{}, diary:{}, plans:{}, pulse:sharedPulseForMutation };",
    prelude: "var sharedPulseForMutation=[];\n" },


  { name: "国別個人記録で継承プロパティを許す", guards: "国別個人記録own property",
    file: "index.html",
    from: "      if(Object.prototype.hasOwnProperty.call(v,c) && v[c] && typeof v[c]===\"object\" && !Array.isArray(v[c])) out[c]=normalizePersonalData(v[c]);",
    to: "      if(v[c] && typeof v[c]===\"object\" && !Array.isArray(v[c])) out[c]=normalizePersonalData(v[c]);" },


  { name: "国切替前の個人記録同期で現在国の正規化を外す", guards: "personal profile切替前同期",
    file: "index.html",
    from: "  const c=Core.normalizeCountry(state.settings.country);\n  state.personalProfiles=normalizePersonalProfiles(state.personalProfiles);",
    to: "  const c=state.settings.country;\n  state.personalProfiles=normalizePersonalProfiles(state.personalProfiles);" },

  { name: "国切替後の個人記録読込で指定国の正規化を外す", guards: "personal profile切替後読込",
    file: "index.html",
    from: "  const c=Core.normalizeCountry(country);\n  state.personalProfiles=normalizePersonalProfiles(state.personalProfiles);",
    to: "  const c=country;\n  state.personalProfiles=normalizePersonalProfiles(state.personalProfiles);" },

  { name: "国切替後の個人記録で未作成国にも現在データを使う", guards: "未作成国personal profile分離",
    file: "index.html",
    from: "  const d=state.personalProfiles[c] ? normalizePersonalData(state.personalProfiles[c]) : emptyPersonalData();",
    to: "  const d=state.personalProfiles[c] ? normalizePersonalData(state.personalProfiles[c]) : normalizePersonalData({health:state.health,diary:state.diary,plans:state.plans,pulse:state.pulse});" },

  { name: "国切替後の個人記録でpulseを切り替えない", guards: "personal profile 4領域切替",
    file: "index.html",
    from: "  state.health=d.health; state.diary=d.diary; state.plans=d.plans; state.pulse=d.pulse;",
    to: "  state.health=d.health; state.diary=d.diary; state.plans=d.plans;" },

];

module.exports = MUTATIONS;
